"use strict";
/**
 * Galerie d'Âges passés par la couche physique (prototype) : écrit docs/physique-exemples.md.
 *   node tools/physics-report.js [fr|en]
 * Pour chaque Âge : le bloc, la fiche, la chaîne de causes, les tensions et leurs pistes, la stabilité
 * du moteur puis en mode strict. Le tirage des pages ouvertes est coupé (draw: false) pour ne montrer
 * que ce qui est écrit.
 */
const fs = require("fs"), path = require("path");
const { analyseAgeBase } = require("../src/engine/analysis");
const P = require("../src/physics");

const lang = process.argv[2] === "en" ? "en" : "fr";
const AGES = [
  ["Terre-mère", "single_sun\nwater\nstone\nrain\nfern\ngrazer", "Le témoin : un monde tempéré, rien ne grince."],
  ["Forge", "lava\nwater\nstone\nash", "La lave demande un intérieur chaud : le tirage choisit un monde jeune ou massif."],
  ["Braise lente", "lava\nash\nmass: 0.2\nage: 9", "Un petit monde très vieux à qui l'on demande des volcans : la physique proteste et propose des lignes."],
  ["Crépuscule", "red_sun\nfrozen_cycle\nwater\nspore\nfern\nwind", "Autour d'une naine rouge, la marée fige la rotation : une face au soleil, l'autre dans la nuit."],
  ["Midi figé", "single_sun\nfrozen_cycle\nwater", "La même face figée autour d'un soleil jaune : peu plausible, et le monde le dit."],
  ["Io", "planet_rings\nlava\nsteam\nwater", "La lune d'une géante, chauffée par ses marées."],
  ["Errante", "starless\nwater\nspore\npale_fungus\ngreat_tree", "Sans étoile : l'eau gèle, les champignons vivent de la chaleur du sol, les arbres non."],
  ["Bleue", "blue_sun\ngreat_tree\ngrazer", "Une étoile bleue vit trop peu pour que l'évolution fasse des arbres…"],
  ["Bleue semée", "blue_sun\ngreat_tree\ngrazer\ntablet\ndoor", "… sauf si des bâtisseurs les ont apportés."],
  ["Mer sans rivage", "ocean_world\nwater\ndrifter\ncompanion_moon", "Un monde-océan, une lune, des dériveurs."],
  ["Poussière", "desert_world\nsand\nwind\ndust_storm\nmass: 0.3", "Un petit désert : assez d'air pour les tempêtes de sable ?"],
  ["Aurores mortes", "auroras\nmass: 0.1\nage: 8", "Des aurores sans champ magnétique."],
  ["Ciel vert", "green_sun\nwater\nfern", "Un soleil vert : pas une faute physique, un coût d'Art."],
  ["Jumeaux", "twin_suns\nwide_binary_orbit\nwater\nfern\nrain", "Deux soleils, une orbite qui fait le tour des deux."],
];

const f = P.fmt(lang);
let out = lang === "fr"
  ? "# Couche physique — galerie d'Âges (prototype)\n\n> Généré par `node tools/physics-report.js`. La physique n'est **pas encore branchée** sur le plugin : ces fiches montrent ce que verrait l'onglet « Physique ». Tirage des pages coupé (seul ce qui est écrit compte). Graine = nom de l'Âge.\n\n"
  : "# Physics layer — gallery of Ages (prototype)\n\n> Generated by `node tools/physics-report.js en`. Physics is **not wired** into the plugin yet. Page drawing off. Seed = Age name.\n\n";
for (const [name, src, note] of AGES) {
  const a = analyseAgeBase(src, { seed: name, draw: false });
  const ph = P.physicsOf(a, src, name), sh = P.sheet(ph, lang), strict = P.applyPhysics(a, ph, "strict");
  out += `## ${name}\n\n*${note}*\n\n\`\`\`age\n${src}\n\`\`\`\n\n`;
  for (const [k, v] of sh.rows) out += `- **${k}** : ${v}\n`;
  if (sh.facts.length) out += `\n${lang === "fr" ? "Pourquoi ce monde est ainsi" : "Why this world is so"} :\n\n` + sh.facts.map((x) => `- ${x}`).join("\n") + "\n";
  if (sh.tensions.length) {
    out += `\n${lang === "fr" ? "Ce qui ne tient pas" : "What does not hold"} :\n\n`;
    for (const t of strict.physics.tensions) {
      const s = sh.tensions.find((x) => x.id === t.id);
      out += `- **${t.severity}** · ${t.axis}${t.counted ? "" : lang === "fr" ? " (déjà compté par le moteur)" : " (already counted by the engine)"} — ${s.why}\n`;
      if (s.fix.length) out += `  - ${lang === "fr" ? "Pistes" : "Ways out"} : ${s.fix.join(" ; ")}\n`;
    }
  } else out += `\n${lang === "fr" ? "Rien ne grince." : "Nothing grinds."}\n`;
  out += `\n${lang === "fr" ? "Stabilité" : "Stability"} : ${a.stability} (${a.verdict}) → ${lang === "fr" ? "strict" : "strict"} ${strict.stability} (${strict.verdict})` +
    ` · ${lang === "fr" ? "monde retenu" : "chosen world"} n° ${ph.candidate + 1}/${48}, ${lang === "fr" ? "coût" : "cost"} ${f(ph.cost)}\n\n`;
}
const file = path.join(__dirname, "..", "docs", lang === "fr" ? "physique-exemples.md" : "physics-examples.md");
fs.writeFileSync(file, out);
console.log("écrit " + path.relative(process.cwd(), file) + ` (${AGES.length} Âges)`);
