"use strict";
// Référence complète, version française (miroir de REF_EN dans guide-ref-en.js : mêmes rubriques, mêmes blocs, mêmes segments de code).
// Quatre parties (`part`), dans cet ordre : set (réglages et commandes), write (ce que l'on écrit), gen (ce que l'Âge produit seul), relto.
const REF_FR = [
  // ---- Réglages ---------------------------------------------------------------------------------------------------
  { id: "setref", part: "set", icon: "sliders-horizontal", title: "Tous les réglages", body: [
    { p: "Réglages › Age Writer › Extensions, en sept pages. Valeurs par défaut entre parenthèses." },
    { h: "Livres & couvertures" },
    { ul: ["Thème cuir des livres (oui) · Onglet couverture (oui)", "Ouvrir le livre dans : onglet principal (défaut), fenêtre, panneau latéral", "À l'ouverture d'un livre : couverture (défaut) ou garder l'onglet courant", "Couvertures des livres : auto (défaut), ornée, classique, sobre, nue", "Livre de liaison en 3 pages (oui)"] },
    { h: "Sons" },
    { ul: ["Sons (général) (oui) · Volume (0,35)", "Livre : Son du livre · Clics du fermoir · Pages tournées (tous activés)", "Âge : Son de liaison (oui)", "Relto : Sons des vues rapprochées · Bourdon de l'Imageur (oui) ; fichiers sons facultatifs pour le bassin, la cheminée, le ronronnement, le miaou", "Ambiance du refuge : minimal / zen (défaut) / complet · Volume du Relto (0,6)"] },
    { h: "Fenêtre de liaison" },
    { ul: ["Onglets dans le bloc Âge (oui)", "Rendu de la fenêtre : classique (défaut) / génératif", "Taille de la fenêtre : normale / grande (défaut) / très grande", "Effet de la fenêtre de liaison : classique (défaut), statique, ondulation, balayage, aléatoire, aucun · Intensité de l'effet (1, de 0,2 à 2)", "Liaisons incertaines (oui)"] },
    { h: "D'ni & chiffres" },
    { ul: ["Langue des extensions : auto, English, Français", "Chiffres : auto / police / fichier de glyphes / dessinés · Police des chiffres (nom)", "Afficher les nombres (oui) · Noms en écriture D'ni (oui)", "Relto en onglets (oui) · Heure D'ni dans le Relto (oui) · Cadre autour des zones cliquables (non)", "Notes de l'arpenteur (Imageur) : complètes / mots seulement (défaut) / aucune"] },
    { h: "Âges & mécanismes" },
    { ul: ["Loi du changement (oui) · Minutes avant que l'encre sèche (15, de 1 à 120) · Guérison par jour (0,05, de 0 à 0,3)", "Ouverture des fissures (7 jours, de 0 à 30)", "Mécanismes : dessinés (défaut) / écrits seulement · Solitude : aucune / équilibrée (défaut) / forte", "Physique des Âges : facile (défaut) / strict / désactivée · Sévérité de la physique (1, de 0,5 à 2)"] },
    { h: "Dossiers" },
    { ul: ["Dossier des journaux (vide = à côté de la note de l'Âge) · Dossier du refuge (`Ages`)"] },
    { h: "Tirage & bibliothèque (réglages du moteur, en anglais)" },
    { ul: ["Update Age data automatically (non) : écrire les propriétés à chaque enregistrement", "Draw the linking panel from the Age (oui) : peindre la vitre d'après l'Âge", "Let the book draw what it leaves open (oui) : tirer les cases ouvertes · How much the book draws : little / normal (défaut) / a lot", "How much a clash steers the draw : none / gentle / moderate (défaut) / strong", "Library folder (vide = tout le coffre) · Default linking panel image"] },
  ] },
  { id: "dni", part: "set", icon: "languages", title: "Chiffres et texte D'ni", body: [
    { p: "Nombres en base 25 (numéro d'Âge, coordonnées, graine, énigmes). Réglage « Chiffres » : auto, police, fichier de glyphes, dessinés. Niveaux : une police installée (famille « Dni ») ou un fichier .ttf/.otf du coffre ; un fichier de glyphes local `dni-numerals.local.json` ; des chiffres dessinés par le plugin (toujours disponibles)." },
    { p: "La police fan n'est ni fournie ni embarquée. Texte D'ni (réglage « Noms en écriture D'ni », police requise) : nom du refuge, plaque d'Âge, titre du journal, couverture, `inscription:`, et en ligne `` `dni:texte` ``. Bloc libre ```` ```dni ```` (une ligne par nombre ou par mot). Sans police : italique latin, jamais de faux D'ni." },
  ] },
  { id: "cmd", part: "set", icon: "terminal", title: "Commandes", body: [
    { p: "Les commandes ne sont pas des réglages : lance-les depuis la palette de commandes (Ctrl/Cmd + P), en tapant quelques mots de leur nom (en anglais)." },
    { ul: ["**Âges** : Generate a random Age (un monde cohérent et stable dans une nouvelle note) · Open this Age as a book · Update Age data in this note / in every note · Save this Age's window as a GIF · Save this Age's book cover (SVG) · Create the exploration journal for this Age · Generate the Age map (canvas) · Open the book of glyphs", "**Bibliothèque** : Create an Age library note · Copy the built-in content into a library note (to edit it) · Reload the Age library · Open a library note (Age blocks / Relto pages)", "**Relto** : Open the Relto · Open the Relto view (large) · Create a Relto page · Stop the soundscape", "**Aide** : Open the Age Writer guide · Open the Age Writer full reference"] },
    { p: "Au premier lancement, une note « Age Writer — Bienvenue » (ou « Welcome ») avec un Âge d'exemple commenté est créée une fois, jamais dans un coffre qui a déjà des Âges." },
    { p: "Limites connues : bureau seulement (mobile non pris en charge) ; la loi du changement range son état par nom de note ; une note à plusieurs blocs `age` tire un monde par bloc ; le contenu du moteur est en anglais ; pas d'export GIF en rendu génératif." },
  ] },

  // ---- Ce que l'on écrit ----------------------------------------------------------------------------------------
  { id: "syntax", part: "write", icon: "pencil", title: "Écrire un Âge", body: [
    { p: "Un Âge est un bloc de code de type `age` dans une note. Chaque ligne se lit seule, et il n'y a que trois sortes de lignes. Un Âge complet peut tenir en si peu :" },
    { code: "```age\nsingle_sun\nwater\nfern\nmass: 0.8\nmany: fern\nreturn: [[Hub]]\n```" },
    { h: "1 · Un bloc : un identifiant seul sur sa ligne" },
    { p: "Un bloc est une page du monde (un soleil, de l'eau, des fougères, une ruine…). Écris son identifiant exactement comme cette référence l'indique : en minuscules, avec des tirets bas, rien avant ni après, un bloc par ligne." },
    { code: "```age\ntwin_suns\nlava\ngreat_tree\n```" },
    { note: "Les listes sont rangées sous des intitulés (Étoiles, Géologie, Faune…). Un intitulé n'est qu'une étiquette : ne l'écris jamais. `stars: twin_suns` est une tache d'encre ; `twin_suns` seul sur sa ligne est juste." },
    { h: "2 · Une ligne clé: valeur" },
    { p: "Une clé, deux-points, une valeur. Pour les liens, la graine, les valeurs physiques, la fenêtre et l'état du livre. La plupart des clés acceptent aussi `=` à la place des deux-points." },
    { code: "```age\nseed: 42\nlink: [[Sunder Reach]]\nage: 3.5\nwindow_style: generative\ndamaged_pages = 2\n```" },
    { h: "3 · Une ligne de liste : une clé, puis plusieurs noms" },
    { p: "Une clé suivie de plusieurs blocs ou noms séparés par des virgules. Pour les quantités et les mécanismes." },
    { code: "```age\nmany: ruins, trees\nfew: rain\nmechanism: water_valve, telescope\n```" },
    { h: "Bon à savoir" },
    { ul: [
      "Les lignes vides et celles qui commencent par `#` sont ignorées : sers-t'en pour tes notes",
      "Une ligne que le plugin ne reconnaît pas est une **tache d'encre** : elle coûte 10 points de stabilité cosmologique, et la fenêtre générative la peint d'après ses mots. Attention à l'orthographe et à la casse : `Water` et `twin suns` sont des taches d'encre",
      "`water` seul sur sa ligne est un bloc (le monde a de l'eau) ; `water: 2` est une valeur physique (combien d'eau). Les deux-points font la différence",
      "Ce que tu n'écris pas est tiré du nom de la note (et de sa ligne `seed:`), toujours de la même façon : voir « Stabilité et tirage »",
      "Les blocs s'ajoutent aussi depuis la palette de la vue livre (commande « Open this Age as a book »)"] },
  ] },
  { id: "sky", part: "write", icon: "sun", title: "Blocs du ciel", check: "blocks", body: [
    { note: "Chaque nom entre accents graves ci-dessous est un bloc : écris-le tel quel, seul sur sa ligne. Le nombre entre parenthèses est son coût en points de stabilité (sur l'axe cosmologique) ; un + rend des points." },
    { code: "```age\ntwin_suns\nred_sun\nwide_binary_orbit\nauroras\nplanet_rings\nmountains\n```" },
    { h: "Étoiles (tirées si tu n'en écris pas)" },
    { ul: ["`single_sun` (−5) : un soleil", "`twin_suns` (−10) : deux soleils", "`starless` (−10) : aucun soleil ; seule la chaleur du sol, et la vie verte peine"] },
    { h: "Lune (parfois tirée)" },
    { ul: ["`companion_moon` (+3) : une lune dans le ciel ; la ligne `moons: 3` en dessine davantage"] },
    { h: "Cycle du jour (tiré si tu n'en écris pas)" },
    { ul: ["`steady_cycle` (−5) : jours et nuits réguliers", "`erratic_cycle` (−8) : jours et nuits de durée inégale", "`frozen_cycle` (−10) : le ciel ne bouge plus ; une face toujours au soleil (il contredit fortement `stable_orbit`, `shifting_orbit` et `chaotic_orbit`)"] },
    { h: "Orbite de deux soleils (jamais tirée)" },
    { p: "Ils décrivent la course de deux soleils : écris-les avec `twin_suns`. Avec un seul soleil ou aucun, ils se contredisent." },
    { ul: ["`close_binary_orbit` (−5) : la planète tourne autour d'un soleil, l'autre reste au loin", "`wide_binary_orbit` (−5) : la planète tourne de loin autour des deux soleils", "`stable_orbit` (−5) : une ronde régulière ; avec deux soleils, il faut aussi `close_binary_orbit` ou `wide_binary_orbit`", "`shifting_orbit` (−8) : la ronde dérive, les éclipses changent", "`chaotic_orbit` (−10) : aucune règle (il contredit fortement `frozen_cycle` et `starless`)"] },
    { h: "Phénomènes (parfois tirés)" },
    { ul: ["`auroras` (−5) : des lueurs dans le ciel ; la physique veut un champ magnétique", "`recurring_eclipses` (−7) : il faut deux soleils, ou un soleil et `companion_moon`", "`permanent_veil` (−6) : un ciel toujours couvert ; 30 % de la lumière seulement passe", "`starfall` (−5) : des pluies d'étoiles filantes"] },
    { h: "Corps célestes (jamais tirés)" },
    { ul: ["`asteroid_belt` (−7) : petits rocs en arc", "`asteroid_field` (−9) : gros blocs, l'un tombe parfois", "`planet_rings` (−2) : une géante annelée emplit le ciel ; ce monde est l'une de ses lunes, chauffée par ses marées", "`comet` (−4) : une comète à longue queue"] },
    { p: "Une ceinture ou un champ menacent ruines, arbres et eau ; un champ pèse plus qu'une ceinture et tombe fort sur un pont." },
    { h: "Couleurs de soleil (jamais tirées)" },
    { p: "Une couleur change le soleil que tu as déjà. Deux couleurs différentes demandent `twin_suns` ; toute couleur contredit `starless`." },
    { ul: ["`red_sun` (−3) : une naine rouge ; elle chauffe plus qu'elle n'éclaire, et les mondes proches lui montrent souvent toujours la même face", "`orange_sun` (−2), `white_sun` (−2) : une étoile plus petite ou plus grosse que le Soleil", "`blue_sun` (−4) : une étoile géante qui vit trop peu pour l'évolution", "`violet_sun` (−5) : une étoile chaude riche en ultraviolets ; vivre à découvert demande un air épais", "`green_sun` (−3) : une étoile solaire à la lumière teintée (feuillages pourpres)", "`black_sun` (−6) : une naine brune ; presque toute sa lumière est infrarouge : jours gris et sombres, disque noir cerclé de rouge, orbite très serrée"] },
    { p: "Les soleils vert et violet n'existent pas parmi les vraies étoiles : en physique stricte, ils coûtent un peu d'Art (axe métaphysique)." },
    { h: "Mondes-types (−2 chacun, jamais tirés)" },
    { p: "`frozen_world`, `lava_world`, `desert_world`, `ocean_world`, `jungle_world`. Ils peignent toute la fenêtre et orientent la physique ; ils ne créent pas de matière. Deux mondes-types se contredisent fortement, et chacun heurte ses contraires (`frozen_world` avec `lava`, `lava_world` avec `deep_cold`…)." },
    { h: "La planète en mots (jamais tirés)" },
    { p: "Des mots à la place des chiffres des valeurs physiques ; chacun vaut une plage." },
    { ul: ["`close_orbit` (−5) / `distant_orbit` (−5) : 1,2 à 2,6 fois la lumière reçue par la Terre, ou 0,12 à 0,6 (ils se contredisent)", "`young_world` (−6) / `ancient_world` (−4) : 50 à 800 millions d'années, intérieur brûlant ; ou 7 à 12 milliards, intérieur refroidi (étoile durable exigée)", "`heavy_world` (−5) / `light_world` (−4) : 2,5 à 8 masses terrestres (gravité forte, montagnes basses), ou 0,06 à 0,35 (gravité faible, air qui fuit)"] },
    { h: "Terrain (jamais tiré)" },
    { ul: ["`plains` (−2) : pays large et bas ; deux chaînes plates dans la fenêtre", "`hills` (−2) : pays doux et ondulé ; trois chaînes douces", "`mountains` (−3) : hauts sommets ; quatre chaînes en arêtes (elles contredisent fortement `plains`, moins `hills`)", "`canyon` (−3) : une gorge profonde ; deux chaînes vives", "`river` (−2), `delta` (−3), `lake` (−2), `marsh` (−2) : de l'eau et un rivage dans la fenêtre (le marais ajoute de la brume) ; ils jurent avec `desert_world` et `lava_world`"] },
    { p: "Il n'y a pas de bloc « désert » : écris `desert_world` ou `sand`." },
  ] },
  { id: "matter", part: "write", icon: "layers", title: "Blocs de matière", check: "blocks", body: [
    { note: "Chaque nom entre accents graves ci-dessous est un bloc : écris-le tel quel, seul sur sa ligne. « Tiré » veut dire que l'Âge peut l'ajouter seul si tu laisses la case ouverte ; les autres n'existent que si tu les écris. Le nombre entre parenthèses est le coût en stabilité sur l'axe du bloc." },
    { code: "```age\nwater\nsand\nfern\ngrazer\ntablet\ngold\nbarren_soil\n```" },
    { h: "Géologie" },
    { ul: ["Sol (un seul tiré au plus) : `water` (−3), `stone` (−2), `sand` (−2), `deep_cold` (−5), `lava` (−6)", "Minéraux (parfois tirés) : `salt` (−3), `ash` (−2), `iron` (−3), `crystal` (−4)", "Jamais tirés : `strange_stone` (−8), un catalyseur qui change les produits des réactions en variantes rares ; `pressure` (−5), une profondeur écrasante"] },
    { h: "Voies de retour (géologiques)" },
    { ul: ["Tirées, une au plus : `fissure` (à l'air libre, ou sous l'eau s'il y a de l'eau), `submarine_fissure` (seulement avec de l'eau), `cave_fissure` (au fond d'une grotte) ; −2 chacune", "`no_fissure` (−2) : il n'y en a pas ; jamais tirée"] },
    { h: "Météo" },
    { ul: ["Parfois tirés : `wind` (−3), `rain` (−3), `fog` (−3), `lightning` (−5), `heat` (−4)", "Jamais tirés : `drizzle` (−2), une bruine qui va et vient ; `snow` (−3), une neige qui tombe sans bruit ; `rainbow` (−2), il lui faut un soleil ; `tornado` (−6), une colonne sombre qui tourne"] },
    { h: "Vivant (écologique)" },
    { ul: ["Flore, parfois tirée : `spore` (−2), `seed` (−2), `fern` (−2), `vine` (−3), `great_tree` (−5) ; jamais tirée : `flowers` (−2), avec `fog` elles parfument la brume, avec `wind` elles tombent en pétales", "Faune, parfois tirée : `moth` (−3), `grazer` (−3), `burrower` (−3), `hunter` (−5), `drifter` (−4)", "Jamais tirés : `kelp` (−2), une forêt sous l'eau ; `coral` (−3), un récif vif en eau chaude ; `spiders` (−3), des tisseuses de soie farouches devant la lumière, qui ont besoin de proies"] },
    { h: "Ruines et lieux (métaphysiques)" },
    { ul: ["Parfois tirés : `tablet` (−3), `lamp` (−3), `bridge` (−3), `door` (−4), `book` (−4)", "Jamais tirés : `library` (−3), une bibliothèque close et pleine ; `ruined_library` (−4), sans toit ; `garden` (−3), un dédale de fleurs"] },
    { p: "Ruines et lieux disent que quelqu'un est passé : la physique pardonne ce que des bâtisseurs ont pu apporter (des arbres sous une étoile trop jeune), jamais la vie impossible (sans lumière, sans air, à une température mortelle)." },
    { h: "Richesses et cicatrices (géologiques, jamais tirées)" },
    { ul: ["Richesses : `gold` (−9), `silver` (−6), `gems` (−7), `rare_ore` (−8), `pearls` (−5), `copper` (−3)", "Cicatrices, gratuites en elles-mêmes : `scorched_surface`, `poisoned_air`, `barren_soil`, `bitter_water`, `hollowed_ground`, `ashen_sky`"] },
    { p: "Chaque cicatrice rend 3 points du coût des richesses, jusqu'à 75 % de ce coût : un monde riche n'est jamais gratuit. Sans richesse, les cicatrices ne font rien." },
    { h: "Intérieur, air, acide (géologiques, jamais tirés)" },
    { ul: ["`molten_core` (−3) / `dead_core` (−4) : un noyau en fusion (champ magnétique), ou mort", "`geysers` (−4) : des sources chaudes ; il faut de l'eau et de la chaleur interne", "`rifts` (−5) : des failles et des plaques qui bougent ; il faut un intérieur chaud, une planète assez grande et de l'eau liquide", "`thick_air` (−3) / `thin_air` (−4) : un air de 2 bars ou plus, ou de moins de 0,3 bar", "`subsurface_ocean` (−4) : un océan sous la glace, chauffé d'en bas", "`acid` (−5) : il ronge : la pierre en sol creux, le fer en rouille, l'eau en eau amère, le corail en sel"] },
  ] },
  { id: "phys", part: "write", icon: "atom", title: "Valeurs physiques", check: "phys", body: [
    { p: "Des lignes facultatives qui fixent les chiffres de la planète. Sans elles, le monde en tire de plausibles d'après sa graine. Écris `clé: nombre` (ou `clé = nombre`) ; la virgule sert de point décimal (`1,5`). Un mot d'unité après le nombre est permis mais ignoré (`1 bar`), sauf `Ma` pour l'âge (`age: 500 Ma`) et `j` ou `jours` pour la rotation (`rotation: 3 j`). Les clés françaises s'écrivent avec ou sans accents (`marées:` ou `marees:`). L'onglet Détails (Physique du monde) montre les valeurs que le monde a reçues." },
    { code: "```age\nsingle_sun\nwater\nmass: 1.2\nage: 3.5\natmosphere: 1.5\ncore: liquid\n```" },
    { table: { head: ["Ligne (autres graphies)", "Valeur type", "Ce que c'est, comment on le mesure"], rows: [
      ["`mass:` (`masse:`)", "`mass: 1`", "La masse de la planète, en Terres (Terre 1, Mars 0,11, une super-Terre 3 à 8). Plus de masse : une gravité plus forte, une planète qui garde plus longtemps son air et sa chaleur. De 0,01 à 20."],
      ["`radius:` (`rayon:`)", "`radius: 1`", "Le rayon de la planète, en rayons terrestres (Terre 1, environ 6 400 km ; Mars 0,53). D'ordinaire on l'omet : il découle de la masse et de la part de fer. De 0,05 à 4."],
      ["`age:` (`âge:`)", "`age: 4.5`", "Le temps écoulé depuis la formation du monde, en milliards d'années (Terre 4,5) ; `age: 500 Ma` fait 500 millions d'années. Un monde jeune est chaud dedans (volcans) ; la vie simple demande au moins 0,3, les arbres et les bêtes au moins 1. Au plus 13,8."],
      ["`orbit:` (`orbite:`, `distance:`)", "`orbit: 1`", "La distance à l'étoile, en unités astronomiques : 1 UA est la distance Terre-Soleil, environ 150 millions de km (Mars 1,5). La lumière reçue découle alors de l'éclat de l'étoile, et `insolation:` est ignorée. De 0,005 à 1 000."],
      ["`insolation:` (`flux:`)", "`insolation: 1`", "La lumière de l'étoile qui arrive sur la planète, comparée à celle que reçoit la Terre (Terre 1, Vénus 1,9, Mars 0,43). C'est elle qui fait la température avant tout. L'eau liquide est la plus facile entre environ 0,36 et 1,1 (la zone habitable)."],
      ["`star_mass:` (`masse_étoile:`)", "`star_mass: 1`", "La masse de l'étoile, en Soleils. Plus légère : plus rouge, plus pâle, presque éternelle (`star_mass: 0.3` est une naine rouge) ; plus lourde : plus blanche, plus brillante, et elle meurt jeune (à 2 Soleils, au bout d'environ 1,3 milliard d'années). De 0,08 à 60."],
      ["`rotation:` (`spin:`)", "`rotation: 24`", "La durée du jour en heures : le temps que met la planète à tourner une fois sur elle-même (Terre 24). `rotation: 3 j` fait trois jours terrestres. Une rotation lente affaiblit le champ magnétique. Ignorée avec `frozen_cycle`."],
      ["`core:` (`noyau:`)", "`core: liquid`", "Le cœur de métal de la planète. En mots : `liquid` (ou `liquide`), `solid` (ou `figé`), `none` (ou `aucun`). En nombre de 0 à 0,8 : la part de la masse de la planète qui est noyau de fer (Terre 0,33). Un noyau liquide qui tourne vite fait un champ magnétique, qui protège l'air et nourrit les aurores."],
      ["`atmosphere:` (`atmosphère:`, `pressure:`, `pression:`)", "`atmosphere: 1`", "La pression de l'air au sol, en bars (Terre 1 au niveau de la mer, Mars 0,006, Vénus 92). En mots : `none` (moins de 0,01), `thin` (0,005 à 0,5), `dense` (3 ou plus) ; aussi `aucune`, `mince`, `épaisse`. Sous 0,006 bar, l'eau ne peut pas rester liquide. Un nombre ici remplace ce que donnerait `volatiles:`."],
      ["`water:` (`eau:`)", "`water: 1`", "La quantité d'eau de la planète, comparée aux océans terrestres (Terre environ 1). C'est une quantité, pas un état : la température et la pression décident si c'est de la mer, de la glace ou de la vapeur. Sans cette ligne elle vaut 0,3, et certains blocs la changent : 1 avec `water`, 3 avec `ocean_world`, 0,02 avec `desert_world`. De 0 à 10."],
      ["`volatiles:`", "`volatiles: 1`", "La réserve de gaz (gaz carbonique, azote, vapeur d'eau) que la roche peut rendre par les volcans pour faire l'air, comparée à la Terre (tirée entre 0,1 et 5). On ne la mesure pas directement : on l'estime d'après ce dont la planète est faite. Ici, la pression de l'air vaut à peu près volatils × activité volcanique × part que la planète arrive à retenir (gravité, champ magnétique). Monte-la pour un air plus épais sans fixer la pression. De 0 à 10."],
      ["`albedo:` (`albédo:`)", "`albedo: 0.3`", "La part de la lumière de l'étoile renvoyée tout droit vers l'espace, de 0 (noir) à 1 (un miroir). Terre 0,3, Lune 0,12, neige fraîche environ 0,8, nuages de Vénus 0,77. Un monde plus clair reste plus froid. Au-delà de 0,9, compte pour 0,9."],
      ["`tides:` (`marées:`)", "`tides: 0.03`", "La chaleur produite dans la planète par les marées, comptée en unités de toute la chaleur interne de la Terre (chaleur interne terrestre = 1). Une lune, une géante ou une étoile proche étire et comprime la roche à chaque tour, et le frottement la chauffe, comme une pâte pétrie dans la main. Ce n'est pas la hauteur des marées de la mer. Sans cette ligne : 0, 0,03 avec `companion_moon`, 0,1 à 5 pour la lune d'une géante (`planet_rings`), un peu plus pour un monde tout près de son étoile. De 0 à 50."],
    ] } },
    { p: "Les nombres fixent une valeur ; les mots (`core: liquid`, `atmosphere: thin`) sont des affirmations que la physique vérifie sans rien fixer (sauf `core: none`, qui donne une planète presque sans fer). Un nombre hors plage y est ramené, et la fiche le dit ; 0 est ignoré là où il n'a pas de sens (masse, rayon, âge, orbite, insolation, masse de l'étoile, rotation)." },
    { p: "La Terre, pour l'échelle : `mass: 1`, `age: 4.5`, `orbit: 1`, `star_mass: 1`, `rotation: 24`, `core: 0.33`, `atmosphere: 1`, `water: 1`, `volatiles: 1`, `albedo: 0.3`. Mars : `mass: 0.11`, `insolation: 0.43`, `atmosphere: 0.006`, `water: 0.3`, `albedo: 0.25`." },
  ] },
  { id: "amounts", part: "write", icon: "gauge", title: "Quantités", body: [
    { p: "Une ligne de quantité rend plus ou moins présent ce qui est déjà écrit. Elle ne crée rien : `many: gold` sans ligne `gold` ne fait rien." },
    { code: "```age\ngreat_tree\nrain\ngold\nmany: trees, gold\nfew: rain\n```" },
    { ul: [
      "Clés : `many:` (aussi `much`, `lots`, `plenty`, `beaucoup`) double ; `few:` (aussi `little`, `peu`) garde 40 % ; `normal:` annule",
      "Après la clé, une ou plusieurs cibles séparées par des virgules : un groupe ou n'importe quel identifiant de bloc",
      "Groupes : `ruins`, `trees`, `water`, `rain`, `fog`, `wind`, `clouds`, `stars`, `moths`, `glow`, `riches`, `scars` (en français : `ruines`, `arbres`, `eau`, `pluie`, `brume`, `vent`, `nuages`, `étoiles`, `richesses`, `cicatrices`)",
      "Un bloc en grande quantité coûte le double de son poids, en petite quantité 40 %. `clouds` et `stars` ne changent que la fenêtre générative"] },
  ] },
  { id: "book", part: "write", icon: "book-open", title: "Liens, graine, état du livre", body: [
    { code: "```age\nreturn: [[Hub]]\nlink: [[Sunder Reach]]\nlink: [[Glass Marsh]]\nseed: 1118\ncover: sober\n```" },
    { ul: [
      "`link: [[Note]]` : un livre de liaison vers un autre Âge ; une ligne par livre",
      "`return: [[Note]]` : le livre de retour, la voie pour rentrer",
      "`panel: [[image.gif]]` : ta propre image dans la vitre de liaison, à la place de la peinte",
      "`seed: 42` : un texte ou un nombre quelconque ; il change le tirage (même note + même graine = même monde)",
      "`cover: sober` : la sobriété de la couverture : `ornate`, `classic`, `sober`, `plain`, ou un nombre de 0 (ornée) à 1 (nue) ; aussi `couverture:`, `cover_style:`, `sobriety:`"] },
    { h: "Un piège ou un livre abîmé" },
    { code: "```age\nwater\ntrap book\ndamaged_pages = 2\nremoved_pages = 1\n```" },
    { ul: [
      "`trap book` seul sur sa ligne (aussi `trap_book`, `livre piège`, `trap: yes`) : ni retour ni fissure ; `trap: no` dit que ce n'est pas un piège",
      "`damaged_pages = 2` : pages abîmées (un nombre entier ; `:` marche aussi)",
      "`removed_pages = 1` : pages arrachées (aussi `torn_pages`)"] },
    { p: "Ce que cela fait à la liaison : voir « Pièges, livres abîmés, liaisons »." },
  ] },
  { id: "weatherlines", part: "write", icon: "cloud-drizzle", title: "Lignes de météo", body: [
    { p: "**Météo vivante.** Une ligne de météo peut dire à quelle fréquence et à quel moment : `drizzle: often, dawn`. Fréquence : `always`, `often`, `sometimes`, `rarely` (ou `toujours`, `souvent`, `parfois`, `rarement`), une fraction (`1/10`) ou un pourcentage (`30%`). Moment : `dawn`, `morning`, `noon`, `afternoon`, `dusk`, `night` (ou `aube`, `matin`, `midi`, `après-midi`, `soir`, `nuit`), un ou plusieurs ; sans moment, à toute heure. Le tirage dépend de la graine de l'Âge et du jour : même Âge, même jour, même temps pour tout le monde. Une ligne `rain` seule reste de la pluie en permanence. Seule la fenêtre générative suit les heures ; la description gagne une phrase (« At dawn, more often than not, a fine drizzle falls. »)." },
    { code: "```age\ndrizzle: often, dawn\nrainbow: sometimes, afternoon\nsnow: rarely, night\nfog: 1/10, night\n```" },
  ] },
  { id: "winlines", part: "write", icon: "app-window", title: "Lignes de la fenêtre", body: [
    { p: "Des lignes qui ne changent que l'aspect de la fenêtre de liaison. Sans elles, ce sont les réglages qui décident." },
    { code: "```age\nwindow_style: generative\nwindow_size: xl\nfx: ripple\nday_length: 40\nyear_length: 12\nmoons: 2\n```" },
    { ul: [
      "`window_style: generative` ou `classic` : un paysage tiré de la graine, ou la fenêtre peinte du moteur ; aussi `render:`",
      "`window_size: large` : `normal`, `large` ou `xl` ; ou `window_width: 520`, une largeur en pixels de 200 à 800",
      "`fx: tv` : l'effet de la fenêtre : `classic`, `static`, `ripple`, `sweep`, `tv`, `random`, `off` ; aussi `window_fx:`, `link_fx:` (deux-points seulement)",
      "`day_length: 40` : minutes réelles par jour de l'Âge, de 0,2 à 1440 ; le soleil suit l'horloge de l'ordinateur (fenêtre générative) ; aussi `day:`",
      "`year_length: 12` : jours par année, de 1 à 365 ; la hauteur du soleil suit les saisons ; demande `day_length` ; aussi `year:`, `revolution:`",
      "`moons: 2` : lunes dessinées dans le ciel, de 0 à 5 (fenêtre générative) ; aussi `lunes:` ; sans elle, `companion_moon` en donne une"] },
  ] },
  { id: "mechlines", part: "write", icon: "cog", title: "Mécanismes", body: [
    { p: "Des machines abandonnées, chacune avec son énigme, montrées dans l'onglet Détails. Une ligne en nomme une ou plusieurs (deux-points seulement) ; espaces et majuscules sont pardonnés (« Water Valve » marche)." },
    { code: "```age\nmechanism: water_valve, telescope\n```" },
    { ul: [
      "Mécanismes : `steam_powered_elevator`, `water_valve`, `telescope`, `sound_lock`, `frequency_array`, `steam_generator`, `holofatic_imager`, `orrery`, `tide_gate`, `wind_organ`, `lens_array`",
      "Autres clés : `dnie_mechanism:`, `puzzle_type:`, `puzzle:`",
      "Un nom inconnu est signalé dans l'onglet Détails. Avec le réglage « Mécanismes : dessinés », l'Âge peut aussi en inventer un ou deux"] },
  ] },
  { id: "lib", part: "write", icon: "library", title: "Tes propres blocs (age-library)", body: [
    { p: "Un bloc de code de type `age-library`, dans n'importe quelle note, ajoute tes propres blocs, réactions et variantes. Une définition par ligne :" },
    { code: "```age-library\nblock moonmilk: pale, thick, patient | geological\nproduct curd: soft, white, sour | geological\nreaction moonmilk + salt -> curd (soothing)\nvariant curd -> watching_curd with crystal\n```" },
    { ul: [
      "`block id: trois, adjectifs | axe` : un bloc que l'on peut écrire dans un bloc `age` ; en option `weight=0.03` après l'axe",
      "`product id: … | axe` : un produit (né d'une réaction, jamais écrit) ; en option `bonus=-0.1`",
      "`reaction a + b -> produit (type)` : types `violent`, `corrosive`, `crystallizing`, `soothing`, `transmuting`, `growing`, `feeding`, `decaying`, `awakening`",
      "`variant produit -> produit_rare with catalyseur` : sans `with`, le catalyseur est `strange_stone`",
      "Axes : `cosmological`, `geological`, `metaphysical`, `weather`, `ecological`"] },
    { p: "Réutiliser un identifiant intégré le remplace. En lecture, le bloc affiche ses erreurs ligne par ligne. Les blocs de bibliothèque ne sont jamais tirés au sort ; la fenêtre les peint d'après leur axe et leurs adjectifs. Commandes : créer une note de bibliothèque, copier le contenu intégré, recharger la bibliothèque." },
  ] },

  // ---- Ce que l'Âge produit seul ---------------------------------------------------------------------------------
  { id: "stab", part: "gen", icon: "activity", title: "Stabilité et tirage", body: [
    { p: "Cinq axes : cosmologique, géologique, météo, écologique, métaphysique (plus `alteration`, la loi du changement). Chaque bloc, contradiction et tache d'encre coûte des points sur son axe. L'Âge prend la stabilité de son axe le plus faible : **75 % ou plus : stable**, **40 à 74 % : instable**, **moins de 40 % : mourant**." },
    { h: "Ce que l'Âge tire quand tu laisses ouvert" },
    { ul: [
      "Onze cases : étoiles, cycle du jour, lune, phénomènes, sol, minéraux, météo, flore, faune, ruines, fissure. Étoiles, cycle, sol et fissure prennent une seule valeur : écris-en une et rien d'autre n'y est tiré (`twin_suns` : pas de soleil tiré). Les autres cases peuvent encore ajouter à ce que tu as écrit",
      "Même note + même `seed:` → même monde ; renommer la note change son monde",
      "Les valeurs ordinaires sortent plus souvent ; ce qui contredirait ou réagirait violemment est moins probable, jamais impossible (réglage du moteur « How much a clash steers the draw »)",
      "Les pages tirées sont marquées dans le livre ; ✓ en garde une comme écrite, × la retire",
      "Le réglage « Solitude » pondère le tirage vers des mondes déserts : plus de ruines et de nature sauvage, moins de chasseurs",
      "Orbite, couleurs de soleil, mondes-types, terrain, richesses, cicatrices et tous les autres blocs marqués « jamais tirés » n'existent que si tu les écris"] },
    { h: "Le retour" },
    { p: "Sans livre de retour **et** sans fissure, l'Âge est un piège. Avec de l'eau, une fissure tirée est sous-marine." },
  ] },
  { id: "react", part: "gen", icon: "flask-conical", title: "Réactions (jamais écrites)", check: "products", body: [
    { p: "Quand deux blocs de l'Âge se rencontrent, ils peuvent réagir et ajouter un produit au monde. Les produits apparaissent seuls dans la description et dans le livre, et peuvent réagir à leur tour." },
    { note: "N'écris jamais un produit : ce n'est pas un bloc, et seul sur sa ligne c'est une tache d'encre. Écris plutôt ses ingrédients (`water` et `lava` donnent `obsidian`)." },
    { h: "Géologie" },
    { ul: ["`obsidian` ← `water` + `lava`", "`ice` ← `water` + `deep_cold`", "`glass` ← `sand` + `lava`", "`rust` ← `water` + `iron`, ou `acid` + `iron`", "`brine` ← `water` + `salt`", "`silt` ← `water` + `ash`", "`diamond` ← `ash` + `pressure`", "`humming_shard` ← `crystal` + `strange_stone`", "`crying_obsidian` ← `salt` + `obsidian`", "`fulgurite` ← `lightning` + `sand`"] },
    { h: "Météo" },
    { ul: ["`storm` ← `rain` + `wind`", "`thunderstorm` ← `storm` + `lightning`", "`marsh_mist` ← `fog` + `water`", "`dust_storm` ← `wind` + `sand`", "`ash_cloud` ← `wind` + `ash`", "`hail` ← `rain` + `deep_cold`", "`steam` ← `rain` + `lava`, ou `heat` + `water`", "`rime` ← `fog` + `deep_cold`", "`meltwater` ← `heat` + `ice`", "`spore_cloud` ← `wind` + `spore`", "`charged_crystal` ← `lightning` + `crystal`", "`scented_mist` ← `fog` + `flowers`", "`petal_rain` ← `wind` + `flowers`", "`glaze` ← `drizzle` + `deep_cold`", "`crystal_rain` ← `drizzle` + `crystal`", "`ash_rain` ← `drizzle` + `ash`", "`acid_rain` ← `drizzle` + `acid`", "`meltwater` et `steam` naissent aussi de `snow` + `heat` et de `snow` + `lava`"] },
    { h: "Vivant" },
    { ul: ["`moss` ← `spore` + `water`", "`lichen` ← `moss` + `deep_cold`", "`pale_fungus` ← `spore` + `ash`", "`sapling` ← `seed` + `water`", "`ironwood` ← `sapling` + `pressure`", "`cinderbloom` ← `seed` + `lava`", "`glowvine` ← `vine` + `crystal`", "`withered_fern` ← `fern` + `salt`, ou `heat` + `fern`", "`charred_grove` ← `great_tree` + `lava`", "`grove` ← `great_tree` + `water`", "`wildfire` ← `lightning` + `great_tree`", "`lantern_moths` ← `moth` + `glowvine`", "`herd` ← `grazer` + `moss`", "`stalking_pack` ← `hunter` + `herd`", "`warren` ← `burrower` + `silt`", "`still_drifter` ← `drifter` + `deep_cold`"] },
    { h: "Ruines" },
    { ul: ["`worn_tablet` ← `tablet` + `water`", "`lit_lamp` ← `lamp` + `crystal`", "`sealed_door` ← `door` + `pressure`", "`blurred_book` ← `book` + `water`", "`fallen_bridge` ← `bridge` + `rust`", "`speaking_tablet` ← `tablet` + `strange_stone`"] },
    { p: "Les réactions violentes coûtent le plus (jusqu'à 25 points) ; les apaisantes, les croissances et les cristallisations rendent quelques points. `acid` change aussi `coral` en `salt`, `stone` en `hollowed_ground` et `water` en `bitter_water` (des blocs qui peuvent aussi s'écrire)." },
    { h: "Variantes rares (avec strange_stone)" },
    { p: "Quand `strange_stone` est dans l'Âge, ces produits se montrent sous leur variante rare :" },
    { ul: ["`whispering_obsidian`, `black_ice`, `singing_glass`, `living_rust`, `clouded_diamond`", "`whispering_storm`, `waiting_thunder`, `watching_mist`, `black_hail`", "`singing_lichen`, `wrong_glowvine`, `whispering_moths`, `watching_herd`, `humming_warren`"] },
  ] },
  { id: "physgen", part: "gen", icon: "orbit", title: "Physique du monde", body: [
    { p: "Sous les blocs, un petit monde physique : étoile, orbite, planète, chaleur interne, noyau, champ magnétique, air, température, eau, lumière. Ce n'est pas une simulation : des lois simplifiées, calées pour que la Terre, Mars, Vénus et la Lune tombent à peu près juste. Ce que le livre laisse ouvert est tiré de la graine, sous contraintes : le monde cherche une physique qui tient ce que tu as écrit (48 essais, toujours les mêmes pour la même graine)." },
    { p: "L'onglet Détails en montre la fiche. Si quelque chose ne tient pas, elle dit pourquoi et propose une ligne à écrire (`age: 3.5`) ; un clic l'écrit dans le bloc." },
    { h: "Modes (Réglages › Âges & mécanismes)" },
    { ul: ["**Facile** (défaut) : la fiche explique, la stabilité ne change jamais. Les mondes-types (`frozen_world`…) orientent le tirage", "**Strict** : chaque tension coûte sur son axe (légère 10, moyenne 20, forte 35 points, au plus 45 par axe), multiplié par le curseur « Sévérité de la physique » (0,5 à 2). Les mondes-types n'orientent plus le tirage : ils sont seulement vérifiés", "**Désactivée** : rien"] },
    { h: "Bâtisseurs" },
    { p: "Les ruines (`tablet`, `door`, `bridge`, `lamp`, `book`, `library`, `garden`…) disent que quelqu'un est passé : il a pu apporter ce que la nature n'aurait pas fait à temps. Elles n'excusent pas la vie impossible. Le Relto est hors physique : c'est la zone sûre." },
  ] },
  { id: "window", part: "gen", icon: "image", title: "Ce que montre la fenêtre", body: [
    { p: "**Rendu** : `classic` (la fenêtre peinte du moteur) ou `generative` (un paysage tiré de la graine : ciel teinté, relief, végétation, météo, reflets, premier plan, un détail habité par Âge). Les blocs inconnus sont peints d'après leur axe et leurs adjectifs." },
    { p: "Dans la fenêtre générative, rien n'est décoratif : tout vient du livre et de sa physique." },
    { ul: ["**Rivages** : de l'eau et de la terre dans le même Âge partagent le bas de l'image ; la rive suit ce qui est écrit : lave (côte noire qui fume), sable (plage et dunes), glace (banquise), pierre ou ruines (rochers), plantes (berge herbeuse). Les mondes-types imposent leur décor et n'ont pas de rive", "**Premier plan** : rochers, branche, arche, lianes, roseaux, feuilles, pilier, stalactites de glace, ou rien ; tiré selon l'Âge (roseaux seulement près de l'eau, glace seulement s'il gèle). Les branches poussent à chaque fois différemment (brûlées, enneigées, moussues, en fleurs, aiguilles…)", "**Physique visible** : la couleur et la taille du soleil viennent de l'étoile et de la distance ; un air mince assombrit le ciel (étoiles en plein jour, peu de nuages), un air épais le rend laiteux ; une gravité forte aplatit le relief, une faible le dresse ; une face figée garde le soleil immobile ; un monde froid ou brûlant se voit", "**Nuits** : chaque Âge a son ciel : deux à quatre constellations, parfois une nébuleuse ou une bande d'étoiles, ses lunes (`moons:`) ; `few: stars` est respecté", "**Sous la surface** : `kelp`, `coral` et `acid` se voient dans l'eau, à leur place"] },
    { p: "**Effets** (`fx:` ou réglage) : `classic` (tremblements, ciel qui vire, fractures selon l'instabilité), `static` (neige), `ripple`, `sweep`, `tv` (vieille télé), `random` (un effet par nom d'Âge), `off`. Intensité de 0,2 à 2 ; `prefers-reduced-motion` est respecté." },
    { p: "**Dégâts** (tirés de la graine du livre) : `damaged_pages` = zones décalées, séparation rouge/cyan, figées ou taches d'encre ; `removed_pages` = trous brûlés avec neige ; instabilité forte = fractures ramifiées. Jusqu'à 12 zones et 6 trous ; `fx: off` les supprime." },
  ] },
  { id: "trap", part: "gen", icon: "triangle-alert", title: "Pièges, livres abîmés, liaisons", body: [
    { ul: ["**Livre-piège** (`trap book`) : ni retour (une ligne `return:` est ignorée) ni fissure ; il a l'air parfaitement normal", "**Livre abîmé** : chaque `damaged_pages` ajoute 0,08 d'instabilité de liaison, chaque `removed_pages` 0,15 (au plus 0,9). Ne touche que la liaison, pas la stabilité de l'Âge. Dès 0,3 apparaît « Écouter les parasites »", "**Liaisons incertaines** (réglage) : au-delà de 30 % d'instabilité de liaison, « open ↗ » ou le clic sur la fenêtre peut vaciller (échec, on réessaie) ou glisser (on arrive dans un autre livre du même Âge). À 85 % : 35 % de vacillements et 24 % d'égarements"] },
  ] },
  { id: "mech", part: "gen", icon: "puzzle", title: "Mécanismes et solitude", body: [
    { p: "Chaque mécanisme a un état (au repos, rouillé, envahi, scellé, fissuré) et une énigme (repère de pression, ordre, angles ou sons), dont les valeurs sont données en chiffres D'ni. Avec le réglage « Mécanismes : dessinés », l'Âge en invente jusqu'à deux, choisis d'après ce qu'il contient (l'eau appelle les vannes, le cristal les serrures sonores…)." },
    { p: "Solitude : aucune (tirage d'origine), équilibrée (ruines ×2,2, flore ×1,3, chasseurs ×0,5), forte (ruines ×3,5, chasseurs ×0,25). Changer ce réglage change les mondes tirés pour les cases ouvertes." },
  ] },
  { id: "journal", part: "gen", icon: "notebook-pen", title: "Journal, couverture, propriétés", body: [
    { ul: ["**Journal** : la commande « Create the exploration journal for this Age » crée une note avec un bloc `age-journal`, écrit d'après les notes qui renvoient à l'Âge. Voix inspirées de personnages des jeux (anglais ou français)", "**Couverture** : un onglet du livre, procédurale (marbre, cuir, laiton, glyphes, médaillon), de la plus ornée à la plus nue ; export SVG", "**Carte** : la commande « Generate the Age map (canvas) » dessine les Âges liés (bleu = aller-retour, orange = sens unique)"] },
    { p: "Propriétés écrites dans la note (commandes « Update Age data… » ou le réglage automatique) : `age_verdict`, `age_stability`, `age_axes`, `age_return`, `age_links`, `age_discovered`, `age_drawn`, `age_home`, utilisables avec Dataview ou Bases." },
  ] },
  { id: "snd2", part: "gen", icon: "volume-2", title: "Les sons", body: [
    { ul: ["**Livre** : choc mat, cuir, pages (« Son du livre »), puis 2 à 5 clics de fermoir (« Clics du fermoir »)", "**Liaison** : onze variantes (A à K) tirées au hasard, jamais la même deux fois de suite, avec hauteur aléatoire, glissando, trémolo, écho, accord", "**Page tournée** : froissement de papier synthétisé", "**Parasites** : souffle à coupures et bourdonnement 50 Hz", "**Ambiances** : vent, pins, eau, cascade, pluie, bourdon, résonance métallique, feu, grillons, tonnerre, nappe, carillon ; niveaux minimal / zen / complet", "**Garde-fou** : l'ambiance s'arrête si la note change, si l'onglet se ferme ou passe à l'arrière-plan ; elle continue quand on change d'onglet à l'intérieur du Relto"] },
  ] },

  // ---- Relto ------------------------------------------------------------------------------------------------------
  { id: "relto2", part: "relto", icon: "mountain", title: "Le refuge : note et bloc", body: [
    { p: "La commande « Open the Relto » crée la note du refuge (dans le dossier du refuge) si besoin. Un bloc de code `relto` montre l'île dans n'importe quelle note :" },
    { code: "```relto\ninscription: Shorah\ntime: 21.5\n```" },
    { h: "Options du bloc relto (une par ligne, toutes facultatives)" },
    { ul: ["`source: [[Relto]]` : la note du refuge (sinon la première note avec `age_type: personal_hub`)", "`time: 21.5` : une heure fixe (sinon l'horloge de l'ordinateur)", "`inscription: Shorah` : une devise sous l'image", "`dni_time: off` : masque l'heure D'ni", "`pages: hide` : replie la liste des pages (mode sans onglets)", "`folders: Ages`, `exclude: Drafts`, `books: Sunder Reach, Glass Marsh` : quels livres sont sur l'étagère (listes séparées par des virgules) ; sinon les cases à cocher de l'onglet Pages, enregistrées en `relto_books` dans la note (`[]` = aucun livre)"] },
    { h: "La note du refuge (propriétés)" },
    { code: "---\nage_type: personal_hub\nage_name: Relto\nseed: 19991118\nenvironment:\n  base_terrain: volcanic_plateau\n  surrounding: cloud_sea\n  sky_cycle: system_time\nstructures: [hut, bookshelves, linking_pillars]\nrelto_pages_active: [page_pine_trees, page_waterfall]\n---" },
    { ul: ["`base_terrain` : volcanic_plateau, mossy_plateau, sand_island, glacier, obsidian_plateau", "`surrounding` : cloud_sea, fog_sea, ocean, void, lava_sea", "`sky_cycle` : system_time, frozen_dawn, frozen_day, frozen_dusk, frozen_night"] },
    { h: "Heure D'ni" },
    { p: "Calculée d'après l'horloge de l'ordinateur : année (hahr), mois (vailee), jour (yahr), puis gahrtahvo : tahvo : gorahn : prorahn, en chiffres D'ni. Un prorahn dure environ 1,39 s." },
  ] },
  { id: "reltopages", part: "relto", icon: "file-plus", title: "Pages du Relto", body: [
    { p: "Chaque page ajoute un élément et une ambiance à l'île. La commande « Create a Relto page » (ou « Nouvelle page » dans l'onglet Pages) l'écrit dans une note ; on l'attache depuis l'onglet Pages." },
    { h: "Pages intégrées" },
    { p: "`page_pine_trees`, `page_birches`, `page_palms`, `page_ferns`, `page_waterfall`, `page_fireflies`, `page_lanterns`, `page_snow`, `page_aurora`, `page_fireworks`, `page_mountain`, `page_pillars`, `page_chimney`, `page_mist`, et sous l'île : `page_gems`, `page_gold`, `page_silver` ; puis `page_rain`, `page_storm`, `page_birds`, `page_butterflies`, `page_moons`, `page_dock`, `page_bench`, `page_islets`, `page_calendar`, `page_flowers`, `page_grass`, `page_ponderosa`, `page_maples`, `page_crystal_tree`, `page_stalk_tree`, `page_koi`, `page_pond_decor`, `page_cat`, `page_cat_toys` et `page_imager`." },
    { h: "Une page = une note" },
    { code: "---\nrelto_page_id: page_pine_trees\ntarget_age: Relto\nenabled: true\neffects:\n  canvas_additions:\n    - { type: vegetation, density: 0.7, asset: conifer }\n  ambiance_audio: wind_in_pines\nunlock:\n  age: \"[[Marais de verre]]\"\n  min_stability: 60\n  ages_count: 3\n---" },
    { p: "Types d'effets : vegetation, waterfall, fireflies, lanterns, snow, aurora, mist, fireworks, mountain, pillars, chimney, gems, gold, silver, koi, cat, rain, storm, birds, butterflies, moons, dock, bench, stalktree, cattoys, ponddecor, islets, calendar, flowers, grass, imager. Ambiances : wind, wind_in_pines, waterfall, river, soft_rain, night_crickets, deep_hum, fire_crackle, hearth, stone_choir, mountain_air, fireworks, metal_chimes, thunder." },
    { p: "États : *active*, *disponible* (bouton Attacher), *verrouillée* (raison affichée), *désactivée*, *manquante*." },
    { h: "Des pages dans un bloc relto-library" },
    { p: "Une page par ligne : `page id: Étiquette | effets | audio=… | unlock=[[Âge]]:60`." },
    { code: "```relto-library\npage lagoon: Lagoon | vegetation 0.5 palm, gold 0.6 | audio=river | unlock=[[Marais de verre]]:60\n```" },
  ] },
  { id: "reltocat", part: "relto", icon: "cat", title: "Le chat, l'Imageur et le télescope", body: [
    { h: "Le chat" },
    { p: "Page `page_cat` : `cat_name`, `cat_color` (black, white, orange, grey, cream, tabby, calico, tuxedo, siamese ou #rrggbb), `cat_sleep` (auto, always, never). En auto, il dort sur le tapis de la cabane surtout la nuit (plus encore avec la page Cheminée) et par pluie, orage ou neige ; le tirage change toutes les demi-heures. Un clic sur lui : il ronronne. Le bassin aux koïs (`page_koi`) a `koi_rare` (ogon, platinum, ghost) et `koi_name`." },
    { h: "L'Imageur" },
    { p: "Page `page_imager` : une machine sur la table de la cabane, puis sa salle. On pose le livre d'un Âge sur le lutrin (‹ › pour changer de livre) et on l'accorde jusqu'à le voir sur l'écran de laiton. Pas d'onglets : un établi et trois postes, chacun avec sa lampe ; un clic pour s'en approcher, la flèche du bas pour reculer." },
    { ul: ["**I · Râtelier à cristaux** : huit cristaux gravés, quatre logements ; on prend un cristal, on le pose (celui qui y était retourne au râtelier). La bonne réponse : les pages écrites du livre, dans l'ordre du bloc (les quatre premières). Faux : l'image se dédouble ; une bonne page à la mauvaise place luit ambre et compte un peu", "**II · Banc optique** : trois verres (rouge, vert, bleu) qui coulissent sur leurs rails = la lumière de son étoile (couleur du soleil, soleil noir, ou sans étoile) ; l'iris à lamelles = la lumière reçue ; le comparateur montre l'étoile à gauche, ton faisceau à droite. Faux : l'image se teinte ou s'assombrit", "**III · Régulateur** : inverseur de polarité, fréquence, amplitude, harmoniques, phase ; tube cathodique et voltmètre. La fréquence vient de la durée du jour, l'amplitude de la pression de l'air, les harmoniques des aurores et du champ magnétique ; la phase dérive avec l'heure (presque plus si le cycle est figé ; un cycle erratique saute toutes les deux heures)"] },
    { p: "La netteté est le produit des trois : il faut tout régler ; la jauge donne l'ensemble. **Verrou** : sur une image nette (lampe ambre), on tire le levier : la machine suit l'Âge seule, les commandes sont tenues, le livre porte une étiquette de laiton sur l'étagère. **Périscope** (verrouillé) : la manivelle tourne la vue (quatre directions, même ciel, autre décor), le levier l'incline (zénith, horizon, sous l'eau s'il y a de l'eau). Indices : le carnet de l'arpenteur sur la table de la cabane, et l'onglet Détails de l'Âge (une note d'arpenteur, plus ou moins précise selon le réglage « Notes de l'arpenteur »). Réglage, verrou et périscope sont gardés par livre." },
    { h: "Le télescope" },
    { p: "Page `page_telescope` : toujours dans le livre des pages, verrouillée tant qu'aucun Âge n'est écrit. Une lunette de laiton au sommet du mont (sans la page Montagnes, elle apporte son rocher) ; un clic pour y regarder. Chaque Relto cache son propre **Great Zero**, tiré de son nom et de sa graine. Deux molettes : **Torahn** (l'angle, dans le sens horaire depuis la ligne du Great Zero, en torantee : un tour en fait 62 500) et **Élévation** (la hauteur par rapport au plan du Great Zero, en shahfeetee ; comme sur le KI, au-dessus du plan le chiffre est négatif) ; la couronne avance de 25 crans, le moyeu d'un cran (100 torantee ou 1 shahfee). Ce sont les unités du système de coordonnées D'ni du Great Zero (GZCS) ; la troisième coordonnée, la distance au Zéro (en shahfeetee), viendra avec une étape suivante. Aucune distance n'est jamais affichée : un pouls dans le verre, qui bat au prorahn D'ni, s'avive et se fait régulier à mesure qu'on approche, une ligne de mots dit ce qu'on voit, une note douce suit chaque geste ; rien ne dit si l'on se rapproche, et le signal scintille d'un battement à l'autre : regarder quelques battements, et comparer. Amener le point dans le petit anneau : le Zéro est trouvé, gravé sur la plaque en chiffres D'ni, et le reste (un clic sur la plaque y ramène les molettes). Tant que le Zéro n'est pas trouvé, le Relto connaît la date D'ni mais pas l'heure : l'heure D'ni voyage sur le pouls du Zéro, et elle s'affiche une fois captée par le télescope." },
  ] },
];

module.exports = { REF_FR };
