"use strict";
// Référence complète, version anglaise (miroir de REF_FR dans guide.js).
const REF_EN = [
  { id: "lines", icon: "list", title: "Lines of the age block", body: [
    { p: "An `age` block contains one page per line (a block identifier) and some special lines. Special lines are ignored by the engine: they do not count as pages." },
    { ul: [
      "`link: [[Note]]`: a linking book to another Age (several allowed)",
      "`return: [[Note]]`: the return book (the way home)",
      "`panel: [[image]]`: a panel image in place of the painted window",
      "`seed: 42`: changes the draw (same note + same seed = same world)",
      "`mechanism: steam_powered_elevator`: a mechanism; also `dnie_mechanism:`, `puzzle_type:`, or a comma-separated list",
      "`fx: tv`: window effect (classic, static, ripple, sweep, tv, random, off); also `window_fx:`, `link_fx:`",
      "`window_style: generative` (or `classic`): window rendering; also `render:`",
      "`window_size: large` (normal, large, xl) or `window_width: 520` (200 to 800 px)",
      "`day_length: 40`: real minutes per day (0.2 to 1440), generative rendering; also `day:`",
      "`year_length: 12`: days per year (1 to 365, needs `day_length`); also `year:`, `revolution:`",
      "`moons: 2` (`lunes:`): number of moons drawn in the sky (0 to 5), generative rendering; without this line, `companion_moon` gives one",
      "`many: ruins, trees` / `few: rain` / `normal: water`: quantities; also `much`, `lots`, `plenty`, `little`, `beaucoup:`, `peu:`",
      "`cover: sober`: cover sobriety (ornate, classic, sober, plain, or 0 to 1); also `couverture:`, `cover_style:`, `sobriety:`",
      "`trap book`: a trap book (no return, no fissure); also `trap_book`, `trap: true`, `livre piège`; `trap: false` cancels it",
      "`damaged_pages = 2`: damaged pages in the link; `removed_pages: 3`: torn-out pages"] },
    { p: "An Age can also be written as YAML properties (see Relto: note, pages, options)." },
  ] },
  { id: "blocks", icon: "layers", title: "All blocks (pages)", body: [
    { p: "Pages you can write, by stability axis. The random draw fills in whatever you leave open." },
    { h: "Cosmological" },
    { ul: ["Stars: `single_sun`, `twin_suns`, `starless`, `companion_moon`", "Cycle: `steady_cycle`, `erratic_cycle`, `frozen_cycle`", "Orbit: `stable_orbit`, `shifting_orbit`, `chaotic_orbit`, `close_binary_orbit`, `wide_binary_orbit`", "Phenomena: `auroras`, `recurring_eclipses`, `permanent_veil`, `starfall`"] },
    { h: "Geological" },
    { p: "`water`, `lava`, `stone`, `sand`, `salt`, `ash`, `iron`, `crystal`, `strange_stone`, `deep_cold`, `pressure`" },
    { p: "Ways home: `fissure`, `cave_fissure`, `submarine_fissure`, `no_fissure`" },
    { h: "Weather" },
    { p: "`wind`, `rain`, `fog`, `lightning`, `heat`" },
    { h: "Ecological" },
    { p: "Flora: `spore`, `seed`, `vine`, `fern`, `great_tree`; fauna: `moth`, `grazer`, `burrower`, `hunter`, `drifter`" },
    { h: "Metaphysical (ruins)" },
    { p: "`tablet`, `lamp`, `bridge`, `door`, `book`" },
    { h: "Reaction products (never written: they arise from combinations)" },
    { ul: ["Geology: `obsidian`, `ice`, `glass`, `rust`, `brine`, `silt`, `diamond`, `humming_shard`, `crying_obsidian`, `whispering_obsidian`, `black_ice`, `singing_glass`, `living_rust`, `clouded_diamond`, `fulgurite`", "Weather: `storm`, `thunderstorm`, `marsh_mist`, `dust_storm`, `ash_cloud`, `hail`, `steam`, `rime`, `meltwater`, `spore_cloud`, `charged_crystal`, `whispering_storm`, `waiting_thunder`, `watching_mist`, `black_hail`", "Life: `moss`, `lichen`, `pale_fungus`, `sapling`, `ironwood`, `cinderbloom`, `glowvine`, `withered_fern`, `charred_grove`, `grove`, `singing_lichen`, `wrong_glowvine`, `lantern_moths`, `herd`, `stalking_pack`, `warren`, `still_drifter`, `whispering_moths`, `watching_herd`, `humming_warren`, `wildfire`", "Ruins: `worn_tablet`, `lit_lamp`, `sealed_door`, `blurred_book`, `fallen_bridge`, `speaking_tablet`"] },
    { p: "Example reactions: water + lava → obsidian; obsidian + salt → crying obsidian. Chains go up to three levels. `strange_stone` is a catalyst that yields rare variants." },
  ] },
  { id: "ext", icon: "sparkles", title: "Extended sky, world types, riches", body: [
    { p: "Blocks added by the extension: they count toward stability, have contradictions and a description, and appear in the book palette, but are **never drawn at random**: you write them, or they do not exist." },
    { h: "Sky" },
    { ul: ["`asteroid_belt` (−7): small rocks in an arc", "`asteroid_field` (−9): big isolated boulders, one of which sometimes falls", "`planet_rings` (−2): a ringed planet", "`comet` (−4): a long-tailed comet", "Coloured suns (modifiers, −2 to −5): `green_sun`, `red_sun`, `white_sun`, `blue_sun`, `orange_sun`, `violet_sun`; `black_sun` (−6): a black sun, a brown dwarf that warms without lighting (grey, dark day; a black disc ringed in red)"] },
    { p: "Contradictions: a belt or a field threatens ruins, trees and water; a coloured sun contradicts `starless` and, with a single sun, any other colour. A field weighs more than a belt; it falls hard on a bridge." },
    { h: "World types (−2, they force the generative scenery)" },
    { p: "`frozen_world`, `lava_world`, `desert_world`, `ocean_world`, `jungle_world`. They do not create matter: they paint it. Two world types contradict each other strongly; each clashes with its opposites (`frozen_world` with `lava`, `lava_world` with `ice`…)." },
    { h: "Riches and scars" },
    { ul: ["Riches (cost on the geological axis): `gold` −9, `silver` −6, `gems` −7, `rare_ore` −8, `pearls` −5, `copper` −3", "Scars (no cost of their own): `scorched_surface`, `poisoned_air`, `barren_soil`, `bitter_water`, `hollowed_ground`, `ashen_sky`"] },
    { p: "Each scar offsets 3 points of the riches' cost, up to 75% of that cost: a rich world is never free. Without riches, scars do nothing." },
  ] },
  { id: "phys", icon: "atom", title: "Physics of the Ages", body: [
    { p: "Beneath the blocks, a small physical world: star, orbit, planet, internal heat, core, magnetic field, air, temperature, water, light. It is not a simulation: simplified laws, tuned so that Earth, Mars, Venus and the Moon come out roughly right. What the book leaves open is drawn from the seed, under constraints: the world looks for a physics that holds what you wrote (48 attempts, always the same for the same seed)." },
    { h: "Modes (Settings › Ages & mechanisms)" },
    { ul: ["**Easy** (default): the sheet explains, stability never changes. World types (`frozen_world`…) steer the draw.", "**Strict**: each tension costs on its axis (light 10, medium 20, heavy 35 points, at most 45 per axis), multiplied by the “Physics severity” slider (0.5 to 2). World types no longer steer the draw: they are only checked.", "**Off**: nothing."] },
    { h: "Value lines (all optional)" },
    { ul: ["`mass:` (`masse:`) Earth = 1 · `radius:` (`rayon:`)", "`age:` (`âge:`) in billions of years, `500 Ma` accepted", "`orbit:` (`orbite:`, `distance:`) in AU · `insolation:` (`flux:`) Earth = 1 · `star_mass:` (`masse_étoile:`) Sun = 1", "`rotation:` in hours, `3 j` accepted", "`core:` (`noyau:`) `liquid` / `liquide`, `solid` / `figé`, `none`, or an iron share from 0 to 0.8", "`atmosphere:` (`atmosphère:`, `pression:`) `none`, `thin` / `mince`, `dense` / `épaisse`, or a figure in bars", "`water:` (`eau:`), `volatiles:`, `albedo:`, `tides:` (`marées:`)", "Given as numbers, the value is fixed; given as words (`core: liquid`), it is a claim that the physics checks. These lines are never ink blots."] },
    { h: "Geophysics blocks (never drawn at random)" },
    { ul: ["`close_orbit` (−5) / `distant_orbit` (−5): very near the star or far from it (they contradict each other)", "`young_world` (−6) / `ancient_world` (−4): under a billion years, burning interior; or 7 to 12, cooled interior (a long-lived star is required)", "`heavy_world` (−5) / `light_world` (−4): a super-Earth (strong gravity, low mountains) or a small world (weak gravity, leaking air)", "`molten_core` (−3) / `dead_core` (−4): a molten core (magnetic field) or a dead one", "`geysers` (−4): hot springs, they need water and internal heat", "`rifts` (−5): faults, moving plates: hot interior, a big enough planet, liquid water", "`thick_air` (−3) / `thin_air` (−4): thick air (≥ 2 bar) or thin", "`subsurface_ocean` (−4): an ocean under the ice, heated from below", "`kelp` (−2): an underwater kelp forest (liquid water and light)", "`coral` (−3): a brightly coloured reef (warm liquid water, light)", "`acid` (−5): an acid (volcanism) that eats away: stone into hollowed ground, iron into rust, water into bitter water, coral into salt", "`black_sun` (−6): a black sun, a brown dwarf; nearly all its light is infrared: grey, dark day, almost black plants, a very tight orbit"] },
    { h: "Sun colours" },
    { p: "`red_sun`: a red dwarf (it warms more than it lights, frozen faces are common); `orange_sun`; `white_sun`; `blue_sun`: a giant star that lives too briefly for evolution; `violet_sun`: a hot star rich in ultraviolet (you need thick air to live in the open); `green_sun`: a sun-like star with tinted light (purple foliage). Green and violet do not exist for real stars: in strict mode they cost a little Art (metaphysical axis)." },
    { h: "Terrain blocks (never drawn at random)" },
    { ul: ["`plains` (−2): wide and low land; two flat ranges in the window", "`hills` (−2): soft, rolling land; three gentle ranges", "`mountains` (−3): tall peaks; four sharp ranges (they contradict `plains` strongly, `hills` less)", "`canyon` (−3): a deep gorge; two sharp ranges", "`river` (−2), `delta` (−3), `lake` (−2), `marsh` (−2): water and a shore in the window (the marsh adds mist); they clash with `desert_world` and `lava_world`", "The desert already exists (`desert_world` or `sand`). Terrain blocks sit in the sky registry, so their cost weighs on the cosmological axis."] },
    { h: "Places and inhabitants" },
    { ul: ["`library` (−3), `ruined_library` (−4), `garden` (−3): metaphysical, traces of builders (the physics reads them like ruins)", "`spiders` (−3): ecological, silk spinners shy of light; they need prey"] },
    { h: "Builders" },
    { p: "Ruins (`tablet`, `door`, `bridge`, `lamp`, `book`…) say that someone passed through: they may have brought what nature could not have made in time (trees under a star that is too young). They do not excuse impossible life (no light, no air, an unlivable temperature)." },
    { p: "The Relto is outside physics: it is the safe zone." },
  ] },
  { id: "amounts", icon: "gauge", title: "Quantities, day and year", body: [
    { p: "A quantity line scales what is already written. Words: `many` / `much` / `lots` / `plenty` / `beaucoup` (×2), `few` / `little` / `peu` (×0.4), `normal` (×1). A block in large quantity costs twice its weight, in small quantity 40%." },
    { p: "Targets: groups `ruins`, `trees`, `water`, `rain`, `fog`, `wind`, `clouds`, `stars`, `moths`, `glow`, `riches`, `scars` (and `ruines`, `arbres`, `eau`, `pluie`, `brume`, `vent`, `étoiles`, `nuages`, `richesses`, `cicatrices`), or any block identifier (`many: gold`). A quantity creates nothing." },
    { p: "`day_length` and `year_length` only change the generative rendering: the sun follows the computer's clock; the year makes its height vary with the season." },
  ] },
  { id: "stab", icon: "activity", title: "Stability and the draw", body: [
    { p: "Five axes: cosmological, geological, weather, ecological, metaphysical (plus the `alteration` axis of the law of change). The Age takes the stability of its weakest axis: **≥ 75% stable**, **40 to 74% unstable**, **< 40% dying**." },
    { ul: ["Everything the book leaves open is drawn (eleven slots: stars, day, moon, phenomena, ground, minerals, weather, flora, fauna, ruins, fissure)", "Same note + same `seed:` → same world; renaming the note changes its world", "Ordinary values come up more often; whatever contradicts or triggers a violent reaction is less likely, never impossible (engine setting “fold strength”)", "The fissure is not guaranteed: with no return book **and** no fissure, the Age is a trap; with water, the fissure is underwater", "“Solitude” setting: weights the draw toward deserted worlds (none / balanced / strong)"] },
  ] },
  { id: "window", icon: "app-window", title: "Window, effects, damage", body: [
    { p: "**Rendering**: `classic` (the engine's painted window) or `generative` (a landscape drawn from the seed: tinted sky, relief, vegetation, weather, reflections, foreground, one inhabited detail per Age). Unknown blocks are painted from their axis and adjectives." },
    { p: "**What the window shows** (generative rendering): nothing in it is decorative, everything comes from the book and its physics." },
    { ul: ["**Shores**: water and land in the same Age share the bottom of the image; the shore follows what is written: lava (a black, smoking coast), sand (beach and dunes), ice (pack ice), stone or ruins (rocks), plants (a grassy bank). World types impose their own scenery and have no shore", "**Foreground**: rocks, branch, arch, vines, reeds, leaves, pillar, ice stalactites, or nothing; drawn according to the Age (reeds only near water, ice only if it freezes). Branches grow differently each time (burnt, snowy, mossy, flowering, needles…)", "**Visible physics**: the colour and size of the sun come from the star and the distance; thin air darkens the sky (stars in daylight, few clouds), thick air makes it milky; strong gravity flattens the relief, weak gravity raises it; a frozen face (locked rotation) keeps the sun still; a cold or burning world shows", "**Nights**: each Age has its own sky: two to four constellations, sometimes a nebula or a band of stars, its moons (`moons:`); `few: stars` is respected", "**Below the surface**: `kelp`, `coral` and `acid` (acidic waters) show in the water, in their place"] },
    { p: "**Effects** (`fx:` or setting): `classic` (tremors, shifting sky, fractures according to instability), `static` (snow), `ripple`, `sweep`, `tv` (old television), `random` (one effect per Age name), `off`. Intensity from 0.2 to 2; `prefers-reduced-motion` is respected." },
    { p: "**Damage** (drawn from the book's seed): `damaged_pages` = shifted zones, red/cyan split, frozen zones or ink blots; `removed_pages` = burnt holes with snow; strong instability = branching fractures. Up to 12 zones and 6 holes; `fx: off` removes them." },
    { p: "**Size**: `window_size` (normal, large, xl) or `window_width` in px; the “Window size” setting is the default." },
  ] },
  { id: "trap", icon: "triangle-alert", title: "Traps, damaged books, links", body: [
    { ul: ["**Trap book**: `trap book`. No return (a `return:` is ignored) and no fissure; it looks perfectly normal", "**Damaged book**: `damaged_pages` (+0.08 linking instability each) and `removed_pages` (+0.15, capped at 0.9). Affects only the link, not the Age's stability. From 0.3 on, “Listen to the static” appears", "**Unreliable links** (setting): beyond 30% linking instability, “open ↗” or a click on the window may waver (it fails, try again) or slip (you arrive in another book of the same Age). At 85%: 35% wavers and 24% strays"] },
  ] },
  { id: "relto2", icon: "mountain", title: "Relto: note, pages, options", body: [
    { h: "The refuge note" },
    { code: "---\nage_type: personal_hub\nage_name: Relto\nseed: 19991118\nenvironment:\n  base_terrain: volcanic_plateau\n  surrounding: cloud_sea\n  sky_cycle: system_time\nstructures: [hut, bookshelves, linking_pillars]\nrelto_pages_active: [page_pine_trees, page_waterfall]\n---" },
    { ul: ["`base_terrain`: volcanic_plateau, mossy_plateau, sand_island, glacier, obsidian_plateau", "`surrounding`: cloud_sea, fog_sea, ocean, void, lava_sea", "`sky_cycle`: system_time, frozen_dawn, frozen_day, frozen_dusk, frozen_night"] },
    { h: "Options of the relto block" },
    { ul: ["`source: Ages/Relto`: the refuge note", "`time: 21.5`: a fixed hour (otherwise the computer's)", "`inscription: texte`: a motto under the image", "`dni_time: off`: hides the D'ni time", "`pages: hide`: collapses the list (tabless mode)", "`folders:`, `exclude:`, `books:`: choice of books on the shelf (comma-separated lists)", "`relto_books` in the note: the list saved by the checkboxes; `[]` = no books"] },
    { h: "Built-in pages" },
    { p: "`page_pine_trees`, `page_birches`, `page_palms`, `page_ferns` (vegetation: conifer, birch, palm, fern), `page_waterfall`, `page_fireflies`, `page_lanterns`, `page_snow`, `page_aurora`, `page_fireworks`, `page_mountain`, `page_pillars`, `page_chimney`, `page_mist`, and under the island: `page_gems`, `page_gold`, `page_silver`; then `page_rain`, `page_storm`, `page_birds`, `page_butterflies`, `page_moons`, `page_dock`, `page_bench`, `page_islets`, `page_calendar`, `page_flowers`, `page_grass`, `page_ponderosa`, `page_maples`, `page_crystal_tree`, `page_stalk_tree`, `page_koi`, `page_pond_decor`, `page_cat`, `page_cat_toys` and `page_imager`." },
    { p: "Effect types: vegetation, waterfall, fireflies, lanterns, snow, aurora, mist, fireworks, mountain, pillars, chimney, gems, gold, silver, koi, cat, rain, storm, birds, butterflies, moons, dock, bench, stalktree, cattoys, ponddecor, islets, calendar, flowers, grass, imager, telescope. Ambiences: wind, wind_in_pines, waterfall, river, soft_rain, night_crickets, deep_hum, fire_crackle, hearth, stone_choir, mountain_air, fireworks, metal_chimes, thunder." },
    { h: "A page = a note" },
    { code: "---\nrelto_page_id: page_pine_trees\ntarget_age: Relto\nenabled: true\neffects:\n  canvas_additions:\n    - { type: vegetation, density: 0.7, asset: conifer }\n  ambiance_audio: wind_in_pines\nunlock:\n  age: \"[[Marais de verre]]\"\n  min_stability: 60\n  ages_count: 3\n---" },
    { p: "States: *active*, *available* (Attach button), *locked* (reason shown), *disabled*, *missing*. `relto-library` block: one page per line, `page lagon: Lagon | vegetation 0.5 palm, gold 0.6 | audio=river | unlock=[[Marais de verre]]:60`." },
    { h: "The cat" },
    { p: "Page `page_cat`: `cat_name`, `cat_color` (black, white, orange, grey, cream, tabby, calico, tuxedo, siamese or #rrggbb), `cat_sleep` (auto, always, never). In auto, it sleeps on the cabin rug mostly at night (even more with the Chimney page) and in rain, storm or snow; the draw changes every half hour. Click it and it purrs." },
    { h: "The Imager" },
    { p: "Page `page_imager`: a machine on the cabin table, then its room. You set an Age's book on the lectern (‹ › to change book) and tune the machine until you see the Age on the brass screen. No tabs: a workbench and three stations, each with its lamp; click to move closer, the down arrow to step back." },
    { ul: ["**I · Crystal rack**: eight engraved crystals, four slots; you pick up a crystal and place it (the one that was there returns to the rack). The right answer: the book's written pages, in block order (the first four). Wrong: the image doubles; a right page in the wrong place glows amber and counts a little", "**II · Optical bench**: three glasses (red, green, blue) that slide on their rails = the light of its star (sun colour, black sun, or no star); the slatted iris = the light received; the comparator shows the star on the left, your beam on the right. Wrong: the image is tinted or darkened", "**III · Regulator**: polarity inverter, frequency, amplitude, harmonics, phase; cathode-ray tube and voltmeter. Frequency comes from the length of the day, amplitude from the air pressure, harmonics from auroras and the magnetic field; the phase drifts with the hour (barely at all if the cycle is frozen; an erratic cycle jumps every two hours)"] },
    { p: "Sharpness is the product of the three: everything must be tuned; the gauge gives the overall figure. **Lock**: on a sharp image (amber lamp), pull the lever: the machine follows the Age on its own, the controls are held, and the book carries a brass tag on the shelf. **Periscope** (locked): the crank turns the view (four directions, same sky, different scenery), the lever tilts it (zenith, horizon, underwater if there is water: kelp, coral, fish, underwater fissure…). Clues: the surveyor's notebook lying on the cabin table, and the Age's Details tab (a surveyor's note: one sentence, and, depending on the “Surveyor's notes” setting, the three values in D'ni numerals; “Words only” by default, “None” to play by ear). Tuning, lock and periscope are kept per book." },
    { h: "The telescope" },
    { p: "Page `page_telescope`: always in the book of pages, locked until you have written a first Age. A brass telescope on top of the mountain (without the Mountains page it brings its own rock); click it to look through. Every Relto hides its own **Great Zero**, drawn from its name and seed. Two wheels: **Torahn** (the angle, clockwise from the Great Zero line, in torantee: a full turn is 62,500) and **Elevation** (height from the Great Zero plane, in shahfeetee; as on the KI, above the plane reads negative); the rim moves 25 notches, the hub one notch (100 torantee or 1 shahfee). These are the D'ni Great Zero Coordinate System (GZCS) units; the third coordinate, the distance from the Zero (in shahfeetee), comes with a later step. No distance is ever shown: a pulse in the glass, beating with the D'ni prorahn, brightens and steadies as you come closer, a line of words says what you see (and whether it brightens or fades), and a soft tone follows each turn. Bring the point into the small ring: the Zero is found, engraved on the plate in D'ni numerals, and stays found (click the plate to set the wheels back on it)." },
    { h: "D'ni time" },
    { p: "Computed from the computer's clock: year (hahr), month (vailee), day (yahr), then gahrtahvo : tahvo : gorahn : prorahn, in D'ni numerals. A prorahn lasts about 1.39 s." },
  ] },
  { id: "dni", icon: "languages", title: "D'ni numerals and text", body: [
    { p: "Base-25 numbers (Age number, coordinates, seed, puzzles). “Numerals” setting: auto, font, glyphs, drawn. Levels: an installed font (family “Dni”) or a .ttf/.otf file from the vault; a local glyph file `dni-numerals.local.json`; numerals drawn by the plugin (always available)." },
    { p: "The fan font is neither supplied nor bundled. D'ni text (setting “Names in D'ni script”, font required): the refuge name, Age plate, journal title, cover, `inscription:`, and inline `` `dni:texte` ``. Free block ```` ```dni ````. Without a font: Latin italics, never fake D'ni." },
  ] },
  { id: "mech", icon: "cog", title: "Mechanisms and solitude", body: [
    { p: "Eleven mechanisms: `steam_powered_elevator`, `water_valve`, `telescope`, `sound_lock`, `frequency_array`, `steam_generator`, `holofatic_imager`, `orrery`, `tide_gate`, `wind_organ`, `lens_array`. Each has a state (rusted, overgrown…) and a puzzle. “Mechanisms” setting: drawn (the Age invents them) or written only." },
    { p: "Solitude: none (the 1.3 draw), balanced (ruins ×2.2, flora ×1.3, hunters ×0.5), strong (ruins ×3.5, hunters ×0.25). Changing this setting changes the worlds drawn for open slots." },
  ] },
  { id: "journal", icon: "notebook-pen", title: "Journal, cover, leather", body: [
    { ul: ["**Journal**: the “Create the exploration journal for this Age” command; an `age-journal` block writes itself from the notes that point back to the Age. Voices inspired by various characters from the games (English or French). Folder adjustable", "**Cover**: a tab of the book, procedural (marble, leather, brass, glyphs, medallion), from the most ornate to the barest; SVG export", "**Leather theme**: dark leather, parchment, brass corners"] },
  ] },
  { id: "snd2", icon: "volume-2", title: "Sounds in detail", body: [
    { ul: ["**Book**: a dull thud, leather, pages (“Book sound”), then 2 to 5 clasp clicks (“Clasp clicks”)", "**Linking**: eleven variants (A to K) drawn at random, never the same twice in a row, with random pitch variation, glissando, tremolo, echo, chord", "**Page turn**: a synthesised paper rustle", "**Static**: breath with dropouts and a 50 Hz hum", "**Ambiences**: wind, pines, water, waterfall, rain, drone, metallic resonance, fire, crickets, thunder, pad, chime; minimal / zen / full levels", "**Safeguard**: the ambience stops if the note changes, if the tab closes or goes to the background; it keeps going when you switch tabs inside the Relto"] },
  ] },
  { id: "lib", icon: "library", title: "Personal library", body: [
    { code: "```age-library\nblock moonmilk: pale, thick, patient | geological\nproduct curd: soft, white, sour | geological\nreaction moonmilk + salt -> curd (soothing)\nvariant curd -> watching_curd with crystal\n```" },
    { p: "Reusing the identifier of a built-in block replaces it. An `age-library` block shows errors line by line in reading view. Commands: create a library note, copy the built-in content, reload. Limit: library blocks are not drawn at random; they are painted from their axis and adjectives." },
  ] },
  { id: "setref", icon: "sliders-horizontal", title: "All settings", body: [
    { h: "Books & covers" },
    { ul: ["Leather theme (on) · Cover tab (on)", "Open the book in: main tab (default), window, side panel", "When opening a book: cover (default) or keep the tab", "Covers: auto, ornate, classic, sober, plain", "3-page linking book (on)"] },
    { h: "Sounds" },
    { ul: ["Sounds (general) · Volume (0.35)", "Book sound · Clasp clicks · Page turning · Linking sound (all on)", "Refuge ambience: minimal / zen (default) / full · Relto volume (0.6)"] },
    { h: "Linking window" },
    { ul: ["Tabs in the Age block (on)", "Window rendering: classic / generative", "Size: normal / large (default) / extra large", "Effect: classic, static, ripple, sweep, random, none · Intensity 0.2 to 2", "Unreliable links (on)"] },
    { h: "D'ni & numbers" },
    { ul: ["Extension language: auto, English, Français", "Numerals: auto / font / glyphs / drawn · Numerals font (name)", "Show numbers · Names in D'ni script", "D'ni time in the Relto · Tabbed Relto"] },
    { h: "Ages & mechanisms" },
    { ul: ["Law of change (on) · Minutes before the ink dries (15, from 1 to 120) · Healing per day (0.05, from 0 to 0.3)", "Mechanisms: drawn / written only · Solitude: none / balanced / strong"] },
    { h: "Folders" },
    { ul: ["Journals folder (empty = next to the Age's note) · Refuge folder (`Ages`)"] },
    { h: "Draw & library (engine settings)" },
    { ul: ["Automatic property update · Generated window · Draw of open slots · Fold strength · Library folder · Default panel image"] },
  ] },
  { id: "cmd", icon: "terminal", title: "Commands and properties", body: [
    { ul: ["Update Age data in this note / in every note: writes the computed properties", "Generate the Age map (canvas): a map of linked Ages (blue = round trip, orange = one way)", "Save this Age's window as a GIF", "Open this Age as a book", "Create / Reload an Age library · Copy the built-in content into a library note", "Open the Relto · Open the Relto view (large) · Create a Relto page", "Generate a random Age: creates a note with a coherent, stable random world (star, water or land, scenery, sometimes moons, auroras, kelp); on first launch, a “Age Writer — Bienvenue” note with an annotated example Age is created once (never in a vault that already has Ages)", "Save this Age's book cover (SVG)", "Create the exploration journal for this Age", "Open the Age Writer guide"] },
    { p: "Properties written in the note: `age_verdict`, `age_stability`, `age_axes`, `age_return`, `age_links`, `age_discovered`, `age_drawn`, `age_home` (usable with Dataview or Bases)." },
    { p: "Known limits: desktop only (mobile is not supported); the law of change stores its state by note name; a note with several `age` blocks draws one world per block; the engine's content is in English; no GIF export in generative rendering." },
  ] },
];

module.exports = { REF_EN };
