"use strict";
// Référence complète, version anglaise (miroir de REF_FR dans guide-ref-fr.js : mêmes rubriques, mêmes blocs, mêmes segments de code).
// Quatre parties (`part`), dans cet ordre : set (réglages et commandes), write (ce que l'on écrit), gen (ce que l'Âge produit seul), relto.
// Blocs : { p } | { h } | { ul } | { code } | { note: encadré « comment l'écrire » } | { table: { head, rows } }
// `check` (facultatif, pour test/reference.test.js) : "blocks" = chaque `identifiant` est un bloc qui s'écrit ;
// "products" = chaque produit est un bloc qui ne s'écrit pas ; "phys" = la colonne 2 du tableau est une ligne de valeur lisible.
const REF_EN = [
  // ---- Réglages ---------------------------------------------------------------------------------------------------
  { id: "setref", part: "set", icon: "sliders-horizontal", title: "All settings", body: [
    { p: "Settings › Age Writer › Extensions, in seven pages. Defaults in brackets." },
    { h: "Books & covers" },
    { ul: ["Leather book theme (on) · Cover tab (on)", "Open the book in: main tab (default), window, side panel", "When a book opens: cover (default) or keep the current tab", "Book covers: auto (default), ornate, classic, sober, plain", "Linking book in 3 pages (on)"] },
    { h: "Sounds" },
    { ul: ["Sounds (all) (on) · Volume (0.35)", "Book: Book sound · Clasp clicks · Page turning (all on)", "Age: Linking sound (on)", "Relto: Sounds of the close-up views · Imager hum (on); optional sound files for the pond, fireplace, purring, meow", "Hub soundscape: minimal / zen (default) / full · Relto volume (0.6)"] },
    { h: "Linking window" },
    { ul: ["Tabs in the Age block (on)", "Window rendering: classic (default) / generative", "Window size: normal / large (default) / extra large", "Linking window effect: classic (default), static, ripple, sweep, random, off · Effect strength (1, from 0.2 to 2)", "Uncertain links (on)"] },
    { h: "D'ni & numbers" },
    { ul: ["Language of the extensions: auto, English, Français", "Numerals: auto / font / glyph file / drawn · Numeral font (name)", "Show numbers (on) · Names in D'ni script (on)", "Relto in tabs (on) · D'ni time in the Relto (on) · Frame around clickable zones (off)", "Surveyor's notes (Imager): full / words only (default) / off"] },
    { h: "Ages & mechanics" },
    { ul: ["Law of change (on) · Minutes before the ink dries (15, from 1 to 120) · Healing per day (0.05, from 0 to 0.3)", "Fissure opening (7 days, from 0 to 30)", "Mechanisms: draw (default) / written only · Solitude: off / balanced (default) / strong", "Physics of the Ages: easy (default) / strict / off · Physics severity (1, from 0.5 to 2)", "Way of the instruments (telescope and Imager): easy (default) / the Art of the Guild"] },
    { h: "Folders" },
    { ul: ["Journal folder (empty = next to the Age's note) · Hub folder (`Ages`)"] },
    { h: "Drawing & library (engine settings)" },
    { ul: ["Update Age data automatically (off): write the properties on every save", "Draw the linking panel from the Age (on): paint the glass from the Age", "Let the book draw what it leaves open (on): draw the open slots · How much the book draws: little / normal (default) / a lot", "How much a clash steers the draw: none / gentle / moderate (default) / strong", "Library folder (empty = whole vault) · Default linking panel image"] },
  ] },
  { id: "dni", part: "set", icon: "languages", title: "D'ni numerals and text", body: [
    { p: "Base-25 numbers (Age number, coordinates, seed, puzzles). “Numerals” setting: auto, font, glyph file, drawn. Levels: an installed font (family “Dni”) or a .ttf/.otf file from the vault; a local glyph file `dni-numerals.local.json`; numerals drawn by the plugin (always available)." },
    { p: "The fan font is neither supplied nor bundled. D'ni text (setting “Names in D'ni script”, font required): the refuge name, Age plate, journal title, cover, `inscription:`, and inline `` `dni:text` ``. Free block ```` ```dni ```` (one line per number or word). Without a font: Latin italics, never fake D'ni." },
  ] },
  { id: "cmd", part: "set", icon: "terminal", title: "Commands", body: [
    { p: "Commands are not settings: run them from the command palette (Ctrl/Cmd + P), by typing a few words of their name." },
    { ul: ["**Ages**: Generate a random Age (a coherent, stable world in a new note) · Open this Age as a book · Update Age data in this note / in every note · Save this Age's window as a GIF · Save this Age's book cover (SVG) · Create the exploration journal for this Age · Generate the Age map (canvas) · Open the book of glyphs", "**Library**: Create an Age library note · Copy the built-in content into a library note (to edit it) · Reload the Age library · Open a library note (Age blocks / Relto pages)", "**Relto**: Open the Relto · Open the Relto view (large) · Create a Relto page · Stop the soundscape · Forget the Great Zero (aim the telescope again)", "**Help**: Open the Age Writer guide · Open the Age Writer full reference"] },
    { p: "On first launch, a “Age Writer — Bienvenue” (or “Welcome”) note with an annotated example Age is created once, never in a vault that already has Ages." },
    { p: "Known limits: desktop only (mobile is not supported); the law of change stores its state by note name; a note with several `age` blocks draws one world per block; the engine's content is in English; no GIF export in generative rendering." },
  ] },

  // ---- Ce que l'on écrit ----------------------------------------------------------------------------------------
  { id: "syntax", part: "write", icon: "pencil", title: "How to write an Age", body: [
    { p: "An Age is a code block of type `age` in a note. Each line is read on its own, and there are only three kinds of line. A whole Age can be this short:" },
    { code: "```age\nsingle_sun\nwater\nfern\nmass: 0.8\nmany: fern\nreturn: [[Hub]]\n```" },
    { h: "1 · A block: one identifier alone on its line" },
    { p: "A block is a page of the world (a sun, water, ferns, a ruin…). Write its identifier exactly as this reference lists it: lowercase, with underscores, nothing before or after it, one block per line." },
    { code: "```age\ntwin_suns\nlava\ngreat_tree\n```" },
    { note: "The lists are sorted under headings (Stars, Geology, Fauna…). A heading is only a label: never write it. `stars: twin_suns` is an ink blot; `twin_suns` alone on its line is right." },
    { h: "2 · A key: value line" },
    { p: "A key, a colon, a value. Used for links, the seed, the physics values, the window and the state of the book. Most keys also accept `=` instead of the colon." },
    { code: "```age\nseed: 42\nlink: [[Sunder Reach]]\nage: 3.5\nwindow_style: generative\ndamaged_pages = 2\n```" },
    { h: "3 · A list line: a key, then several names" },
    { p: "A key followed by several blocks or names separated by commas. Used by quantities and mechanisms." },
    { code: "```age\nmany: ruins, trees\nfew: rain\nmechanism: water_valve, telescope\n```" },
    { h: "Good to know" },
    { ul: [
      "Empty lines and lines starting with `#` are ignored: use them as notes to yourself",
      "A line the plugin does not recognise is an **ink blot**: it costs 10 points of cosmological stability, and the generative window paints it from its words. Mind the spelling and the case: `Water` and `twin suns` are ink blots",
      "`water` alone on its line is a block (the world has water); `water: 2` is a physics value (how much water). The colon makes the difference",
      "Whatever you leave unwritten is drawn from the note's name (and its `seed:` line), always the same way: see “Stability and the draw”",
      "Blocks can also be added from the palette of the book view (command “Open this Age as a book”)"] },
  ] },
  { id: "sky", part: "write", icon: "sun", title: "Sky blocks", check: "blocks", body: [
    { note: "Every name in backticks below is a block: write it as-is, alone on its line. The number in brackets is its cost in stability points (on the cosmological axis); a + gives points back." },
    { code: "```age\ntwin_suns\nred_sun\nwide_binary_orbit\nauroras\nplanet_rings\nmountains\n```" },
    { h: "Stars (drawn if you write none)" },
    { ul: ["`single_sun` (−5): one sun", "`twin_suns` (−10): two suns", "`starless` (−10): no sun at all; only the ground's own heat, and green life struggles"] },
    { h: "Moon (sometimes drawn)" },
    { ul: ["`companion_moon` (+3): a moon in the sky; the line `moons: 3` draws more of them"] },
    { h: "Day cycle (drawn if you write none)" },
    { ul: ["`steady_cycle` (−5): regular days and nights", "`erratic_cycle` (−8): days and nights of uneven length", "`frozen_cycle` (−10): the sky never moves; one face always to the sun (it clashes strongly with `stable_orbit`, `shifting_orbit` and `chaotic_orbit`)"] },
    { h: "Orbit of two suns (never drawn)" },
    { p: "These describe how two suns move: write them with `twin_suns`. With one sun or none they clash." },
    { ul: ["`close_binary_orbit` (−5): the planet circles one sun, the other stays far away", "`wide_binary_orbit` (−5): the planet circles both suns from far out", "`stable_orbit` (−5): a steady round; with two suns it also needs `close_binary_orbit` or `wide_binary_orbit`", "`shifting_orbit` (−8): the round drifts, eclipses change", "`chaotic_orbit` (−10): no rule at all (it clashes strongly with `frozen_cycle` and `starless`)"] },
    { h: "Phenomena (sometimes drawn)" },
    { ul: ["`auroras` (−5): lights in the sky; the physics wants a magnetic field", "`recurring_eclipses` (−7): needs two suns, or one sun and `companion_moon`", "`permanent_veil` (−6): a sky always overcast; only 30% of the light gets through", "`starfall` (−5): showers of shooting stars"] },
    { h: "Sky bodies (never drawn)" },
    { ul: ["`asteroid_belt` (−7): small rocks in an arc", "`asteroid_field` (−9): big boulders, one of which sometimes falls", "`planet_rings` (−2): a ringed giant fills the sky; this world is one of its moons, warmed by its tides", "`comet` (−4): a long-tailed comet"] },
    { p: "A belt or a field threatens ruins, trees and water; a field weighs more than a belt and falls hard on a bridge." },
    { h: "Dead stars (never drawn)" },
    { p: "These are already out there, written or not: every region of space holds them or not, and nearby stars share them. Writing one only describes it: the book then names a world whose star has one nearby (if the star you wrote has none, the world is placed by another star that does; rewriting moves the world). At the telescope they perturb the Great Zero's signal (see the Relto part)." },
    { ul: ["`pulsar` (−6): a fast-spinning dead star whose beam sweeps the sky; a second, faster beat crosses the Zero's pulse; hard on life (light, ecological)", "`neutron_star` (−5): a small, heavy, blue-white ember; a second, slower beat drags under the Zero's", "`black_hole` (−8): a ring of light around an empty dark; it bends the Zero's light (the direction seen from the Age is wrong); it unsettles `stable_orbit` (light)"] },
    { h: "Sun colours (never drawn)" },
    { p: "A colour changes the sun you already have. Two different colours need `twin_suns`; any colour clashes with `starless`." },
    { ul: ["`red_sun` (−3): a red dwarf; it warms more than it lights, and close worlds often keep one face to it", "`orange_sun` (−2), `white_sun` (−2): a smaller or a bigger star than the Sun", "`blue_sun` (−4): a giant star that lives too briefly for evolution", "`violet_sun` (−5): a hot star rich in ultraviolet; life in the open needs thick air", "`green_sun` (−3): a sun-like star with tinted light (purple foliage)", "`black_sun` (−6): a brown dwarf; nearly all its light is infrared: grey, dark days, a black disc rimmed with red, a very tight orbit"] },
    { p: "Green and violet suns do not exist among real stars: in strict physics mode they cost a little Art (metaphysical axis)." },
    { h: "World types (−2 each, never drawn)" },
    { p: "`frozen_world`, `lava_world`, `desert_world`, `ocean_world`, `jungle_world`. They paint the whole window and steer the physics; they create no matter. Two world types clash strongly, and each clashes with its opposites (`frozen_world` with `lava`, `lava_world` with `deep_cold`…)." },
    { h: "The planet in words (never drawn)" },
    { p: "Words instead of numbers for the physics values; each one stands for a range." },
    { ul: ["`close_orbit` (−5) / `distant_orbit` (−5): 1.2 to 2.6 times Earth's sunlight, or 0.12 to 0.6 (they clash with each other)", "`young_world` (−6) / `ancient_world` (−4): 50 to 800 million years old, interior burning; or 7 to 12 billion, interior cooled (needs a long-lived star)", "`heavy_world` (−5) / `light_world` (−4): 2.5 to 8 Earth masses (strong gravity, low mountains), or 0.06 to 0.35 (weak gravity, leaking air)"] },
    { h: "Terrain (never drawn)" },
    { ul: ["`plains` (−2): wide, low land; two flat ranges in the window", "`hills` (−2): soft, rolling land; three gentle ranges", "`mountains` (−3): tall peaks; four sharp ranges (they clash strongly with `plains`, less with `hills`)", "`canyon` (−3): a deep gorge; two sharp ranges", "`river` (−2), `delta` (−3), `lake` (−2), `marsh` (−2): water and a shore in the window (the marsh adds mist); they clash with `desert_world` and `lava_world`"] },
    { p: "There is no desert block: use `desert_world` or `sand`." },
  ] },
  { id: "matter", part: "write", icon: "layers", title: "Matter blocks", check: "blocks", body: [
    { note: "Every name in backticks below is a block: write it as-is, alone on its line. “Drawn” means the Age may add it by itself when you leave that slot open; the others only exist if you write them. The number in brackets is the stability cost on the block's own axis." },
    { code: "```age\nwater\nsand\nfern\ngrazer\ntablet\ngold\nbarren_soil\n```" },
    { h: "Geology" },
    { ul: ["Ground (one drawn at most): `water` (−3), `stone` (−2), `sand` (−2), `deep_cold` (−5), `lava` (−6)", "Minerals (sometimes drawn): `salt` (−3), `ash` (−2), `iron` (−3), `crystal` (−4)", "Never drawn: `strange_stone` (−8), a catalyst that turns reaction products into rare variants; `pressure` (−5), crushing depth"] },
    { h: "Ways home (geological)" },
    { ul: ["Drawn, one at most: `fissure` (in the open, or underwater if there is water), `submarine_fissure` (only with water), `cave_fissure` (deep in a cavern); −2 each", "`no_fissure` (−2): there is none; never drawn"] },
    { h: "Weather" },
    { ul: ["Sometimes drawn: `wind` (−3), `rain` (−3), `fog` (−3), `lightning` (−5), `heat` (−4)", "Never drawn: `drizzle` (−2), a fine rain that comes and goes; `snow` (−3), it falls without a sound; `rainbow` (−2), it needs a sun; `tornado` (−6), a dark spinning column"] },
    { h: "Life (ecological)" },
    { ul: ["Flora, sometimes drawn: `spore` (−2), `seed` (−2), `fern` (−2), `vine` (−3), `great_tree` (−5); never drawn: `flowers` (−2), with `fog` they scent the mist, with `wind` they fall as petals", "Fauna, sometimes drawn: `moth` (−3), `grazer` (−3), `burrower` (−3), `hunter` (−5), `drifter` (−4)", "Never drawn: `kelp` (−2), an underwater forest; `coral` (−3), a bright reef in warm water; `spiders` (−3), silk spinners shy of light, they need prey"] },
    { h: "Ruins and places (metaphysical)" },
    { ul: ["Sometimes drawn: `tablet` (−3), `lamp` (−3), `bridge` (−3), `door` (−4), `book` (−4)", "Never drawn: `library` (−3), a shut library full of books; `ruined_library` (−4), roofless; `garden` (−3), a maze of flowers"] },
    { p: "Ruins and places say that someone passed through: the physics forgives what builders could have brought (trees under a star too young), never impossible life (no light, no air, a deadly temperature)." },
    { h: "Riches and scars (geological, never drawn)" },
    { ul: ["Riches: `gold` (−9), `silver` (−6), `gems` (−7), `rare_ore` (−8), `pearls` (−5), `copper` (−3)", "Scars, free on their own: `scorched_surface`, `poisoned_air`, `barren_soil`, `bitter_water`, `hollowed_ground`, `ashen_sky`"] },
    { p: "Each scar gives back 3 points of the riches' cost, up to 75% of it: a rich world is never free. Without riches, scars do nothing." },
    { h: "Interior, air, acid (geological, never drawn)" },
    { ul: ["`molten_core` (−3) / `dead_core` (−4): a molten core (magnetic field), or a dead one", "`geysers` (−4): hot springs; they need water and inner heat", "`rifts` (−5): faults and moving plates; they need a hot interior, a big enough planet and liquid water", "`thick_air` (−3) / `thin_air` (−4): air of 2 bar or more, or under 0.3 bar", "`subsurface_ocean` (−4): an ocean under the ice, warmed from below", "`acid` (−5): eats away: stone into hollowed ground, iron into rust, water into bitter water, coral into salt"] },
  ] },
  { id: "phys", part: "write", icon: "atom", title: "Physics values", check: "phys", body: [
    { p: "Optional lines that set the planet's numbers. Leave them out and the world draws plausible ones from its seed. Write `key: number` (or `key = number`); a comma works as a decimal point (`1,5`). A unit word after the number is allowed but ignored (`1 bar`), except `Ma` for the age (`age: 500 Ma`) and `d` or `days` for the rotation (`rotation: 3 d`). French keys work with or without accents (`marées:` or `marees:`). The Details tab (Physics of the world) shows the values the world ended up with." },
    { code: "```age\nsingle_sun\nwater\nmass: 1.2\nage: 3.5\natmosphere: 1.5\ncore: liquid\n```" },
    { table: { head: ["Line (other spellings)", "Typical value", "What it is, how it is measured"], rows: [
      ["`mass:` (`masse:`)", "`mass: 1`", "The planet's mass, in Earths (Earth 1, Mars 0.11, a super-Earth 3 to 8). More mass: stronger gravity, and a planet that keeps its air and its inner heat longer. From 0.01 to 20."],
      ["`radius:` (`rayon:`)", "`radius: 1`", "The planet's radius, in Earth radii (Earth 1, about 6,400 km; Mars 0.53). Usually left out: it follows from the mass and the iron share. From 0.05 to 4."],
      ["`age:` (`âge:`)", "`age: 4.5`", "Time since the world formed, in billions of years (Earth 4.5); `age: 500 Ma` is 500 million years. A young world is hot inside (volcanoes); simple life needs at least 0.3, trees and animals at least 1. At most 13.8."],
      ["`orbit:` (`orbite:`, `distance:`)", "`orbit: 1`", "Distance from the star, in astronomical units: 1 AU is the Earth–Sun distance, about 150 million km (Mars 1.5). The light received then follows from the star's brightness, and `insolation:` is ignored. From 0.005 to 1000."],
      ["`insolation:` (`flux:`)", "`insolation: 1`", "How much starlight reaches the planet, compared with Earth (Earth 1, Venus 1.9, Mars 0.43). It sets the temperature more than anything else. Liquid water is easiest between about 0.36 and 1.1 (the habitable zone)."],
      ["`star_mass:` (`masse_étoile:`)", "`star_mass: 1`", "Mass of the star, in Suns. Lighter stars are redder, dimmer and almost eternal (`star_mass: 0.3` is a red dwarf); heavier ones are whiter, brighter and die young (at 2 Suns, after about 1.3 billion years). From 0.08 to 60."],
      ["`rotation:` (`spin:`)", "`rotation: 24`", "Length of the day in hours: the time the planet takes to turn once on itself (Earth 24). `rotation: 3 d` is three Earth days. A slow spin weakens the magnetic field. Ignored with `frozen_cycle`."],
      ["`core:` (`noyau:`)", "`core: liquid`", "The metal heart of the planet. In words: `liquid` (or `liquide`), `solid` (or `figé`), `none` (or `aucun`). As a number from 0 to 0.8: the share of the planet's mass that is iron core (Earth 0.33). A liquid core that turns fast makes a magnetic field, which shields the air and feeds auroras."],
      ["`atmosphere:` (`atmosphère:`, `pressure:`, `pression:`)", "`atmosphere: 1`", "Air pressure at the ground, in bars (Earth 1 at sea level, Mars 0.006, Venus 92). In words: `none` (under 0.01), `thin` (0.005 to 0.5), `dense` (3 or more); also `aucune`, `mince`, `épaisse`. Under 0.006 bar, water cannot stay liquid. A number here replaces what `volatiles:` would give."],
      ["`water:` (`eau:`)", "`water: 1`", "How much water the planet holds, compared with Earth's oceans (Earth about 1). It is an amount, not a state: temperature and pressure decide whether it is sea, ice or vapour. Without this line it is 0.3, and some blocks change it: 1 with `water`, 3 with `ocean_world`, 0.02 with `desert_world`. From 0 to 10."],
      ["`volatiles:`", "`volatiles: 1`", "The stock of gases (carbon dioxide, nitrogen, water vapour) that the rock can breathe out through volcanoes to build the air, compared with Earth (drawn between 0.1 and 5). It cannot be measured directly: it is estimated from what a planet is made of. Here, air pressure is roughly volatiles × volcanic activity × the share the planet can hold on to (gravity, magnetic field). Raise it for thicker air without fixing the pressure. From 0 to 10."],
      ["`albedo:` (`albédo:`)", "`albedo: 0.3`", "The share of starlight bounced straight back to space, from 0 (black) to 1 (a mirror). Earth 0.3, the Moon 0.12, fresh snow about 0.8, the clouds of Venus 0.77. A brighter world stays cooler. Values above 0.9 count as 0.9."],
      ["`tides:` (`marées:`)", "`tides: 0.03`", "Heat made inside the planet by tides, counted in units of Earth's whole inner heat (Earth's inner heat = 1). A nearby moon, giant planet or star stretches and squeezes the rock at every turn, and the friction warms it, like putty kneaded in the hand. It is not the height of sea tides. Without this line: 0, 0.03 with `companion_moon`, 0.1 to 5 for the moon of a giant (`planet_rings`), a little more for a world very close to its star. From 0 to 50."],
    ] } },
    { p: "Numbers fix a value; words (`core: liquid`, `atmosphere: thin`) are claims that the physics checks without fixing anything (except `core: none`, which sets a planet with almost no iron). A number out of range is brought back into it, and the sheet says so; 0 is ignored where it means nothing (mass, radius, age, orbit, insolation, star mass, rotation)." },
    { p: "Earth, for scale: `mass: 1`, `age: 4.5`, `orbit: 1`, `star_mass: 1`, `rotation: 24`, `core: 0.33`, `atmosphere: 1`, `water: 1`, `volatiles: 1`, `albedo: 0.3`. Mars: `mass: 0.11`, `insolation: 0.43`, `atmosphere: 0.006`, `water: 0.3`, `albedo: 0.25`." },
  ] },
  { id: "amounts", part: "write", icon: "gauge", title: "Quantities", body: [
    { p: "A quantity line makes something already written more or less present. It creates nothing: `many: gold` without a `gold` line does nothing." },
    { code: "```age\ngreat_tree\nrain\ngold\nmany: trees, gold\nfew: rain\n```" },
    { ul: [
      "Keys: `many:` (also `much`, `lots`, `plenty`, `beaucoup`) doubles; `few:` (also `little`, `peu`) keeps 40%; `normal:` cancels",
      "After the key, one or more targets separated by commas: a group or any block identifier",
      "Groups: `ruins`, `trees`, `water`, `rain`, `fog`, `wind`, `clouds`, `stars`, `moths`, `glow`, `riches`, `scars` (French: `ruines`, `arbres`, `eau`, `pluie`, `brume`, `vent`, `nuages`, `étoiles`, `richesses`, `cicatrices`)",
      "A block in large quantity costs twice its weight, in small quantity 40%. `clouds` and `stars` only change the generative window"] },
  ] },
  { id: "book", part: "write", icon: "book-open", title: "Links, seed, state of the book", body: [
    { code: "```age\nreturn: [[Hub]]\nlink: [[Sunder Reach]]\nlink: [[Glass Marsh]]\nseed: 1118\ncover: sober\n```" },
    { ul: [
      "`link: [[Note]]`: a linking book to another Age; one line per book",
      "`return: [[Note]]`: the return book, the way home",
      "`panel: [[image.gif]]`: your own image in the linking panel, instead of the painted one",
      "`seed: 42`: any text or number; it changes the draw (same note + same seed = same world)",
      "`cover: sober`: the cover's sobriety: `ornate`, `classic`, `sober`, `plain`, or a number from 0 (ornate) to 1 (bare); also `couverture:`, `cover_style:`, `sobriety:`"] },
    { h: "A trap or a damaged book" },
    { code: "```age\nwater\ntrap book\ndamaged_pages = 2\nremoved_pages = 1\n```" },
    { ul: [
      "`trap book` alone on its line (also `trap_book`, `livre piège`, `trap: yes`): no return, no fissure; `trap: no` says it is not a trap",
      "`damaged_pages = 2`: damaged pages (a whole number; `:` works too)",
      "`removed_pages = 1`: torn-out pages (also `torn_pages`)"] },
    { p: "What these do to the link is in “Traps, damaged books, links”." },
  ] },
  { id: "weatherlines", part: "write", icon: "cloud-drizzle", title: "Weather lines", body: [
    { p: "**Living weather.** A weather line can say how often and when: `drizzle: often, dawn`. How often: `always`, `often`, `sometimes`, `rarely` (French: `toujours`, `souvent`, `parfois`, `rarement`), a fraction (`1/10`) or a percentage (`30%`). When: `dawn`, `morning`, `noon`, `afternoon`, `dusk`, `night` (French: `aube`, `matin`, `midi`, `après-midi`, `soir`, `nuit`), one or several; none = any time. The draw depends on the Age's seed and the day: same Age, same day, same weather for everyone. A bare `rain` line still means rain all the time. Only the generative window follows the hours; the description gains a sentence (“At dawn, more often than not, a fine drizzle falls.”)." },
    { code: "```age\ndrizzle: often, dawn\nrainbow: sometimes, afternoon\nsnow: rarely, night\nfog: 1/10, night\n```" },
  ] },
  { id: "winlines", part: "write", icon: "app-window", title: "Window lines", body: [
    { p: "Lines that change only how the linking window looks. Without them, the settings decide." },
    { code: "```age\nwindow_style: generative\nwindow_size: xl\nfx: ripple\nday_length: 40\nyear_length: 12\nmoons: 2\n```" },
    { ul: [
      "`window_style: generative` or `classic`: a landscape drawn from the seed, or the engine's painted window; also `render:`",
      "`window_size: large`: `normal`, `large` or `xl`; or `window_width: 520`, a width in pixels from 200 to 800",
      "`fx: tv`: the window effect: `classic`, `static`, `ripple`, `sweep`, `tv`, `random`, `off`; also `window_fx:`, `link_fx:` (colon only)",
      "`day_length: 40`: real minutes per day of the Age, from 0.2 to 1440; the sun follows your computer's clock (generative window); also `day:`",
      "`year_length: 12`: days per year, from 1 to 365; the sun's height follows the seasons; needs `day_length`; also `year:`, `revolution:`",
      "`moons: 2`: moons drawn in the sky, from 0 to 5 (generative window); also `lunes:`; without it, `companion_moon` gives one"] },
  ] },
  { id: "mechlines", part: "write", icon: "cog", title: "Mechanisms", body: [
    { p: "Abandoned machines with a puzzle, shown in the Details tab. A line names one or several (colon only); spaces and capitals are forgiven (“Water Valve” works)." },
    { code: "```age\nmechanism: water_valve, telescope\n```" },
    { ul: [
      "Mechanisms: `steam_powered_elevator`, `water_valve`, `telescope`, `sound_lock`, `frequency_array`, `steam_generator`, `holofatic_imager`, `orrery`, `tide_gate`, `wind_organ`, `lens_array`",
      "Other keys: `dnie_mechanism:`, `puzzle_type:`, `puzzle:`",
      "An unknown name is flagged in the Details tab. With the setting “Mechanisms: draw”, the Age may also invent one or two"] },
  ] },
  { id: "lib", part: "write", icon: "library", title: "Your own blocks (age-library)", body: [
    { p: "A code block of type `age-library`, in any note, adds your own blocks, reactions and variants. One definition per line:" },
    { code: "```age-library\nblock moonmilk: pale, thick, patient | geological\nproduct curd: soft, white, sour | geological\nreaction moonmilk + salt -> curd (soothing)\nvariant curd -> watching_curd with crystal\n```" },
    { ul: [
      "`block id: three, adjectives | axis`: a block you can write in an `age` block; optionally `weight=0.03` after the axis",
      "`product id: … | axis`: a product (born of a reaction, never written); optionally `bonus=-0.1`",
      "`reaction a + b -> product (type)`: types `violent`, `corrosive`, `crystallizing`, `soothing`, `transmuting`, `growing`, `feeding`, `decaying`, `awakening`",
      "`variant product -> rare_product with catalyst`: without `with`, the catalyst is `strange_stone`",
      "Axes: `cosmological`, `geological`, `metaphysical`, `weather`, `ecological`"] },
    { p: "Reusing a built-in identifier replaces it. In reading view the block shows its errors line by line. Library blocks are never drawn at random; the window paints them from their axis and adjectives. Commands: create a library note, copy the built-in content, reload the library." },
  ] },

  // ---- Ce que l'Âge produit seul ---------------------------------------------------------------------------------
  { id: "stab", part: "gen", icon: "activity", title: "Stability and the draw", body: [
    { p: "Five axes: cosmological, geological, weather, ecological, metaphysical (plus `alteration`, from the law of change). Every block, clash and ink blot costs points on its axis. The Age takes the stability of its weakest axis: **75% or more: stable**, **40 to 74%: unstable**, **under 40%: dying**." },
    { h: "What the Age draws when you leave it open" },
    { ul: [
      "Eleven slots: stars, day cycle, moon, phenomena, ground, minerals, weather, flora, fauna, ruins, fissure. Stars, day cycle, ground and fissure take one value: write one and nothing else is drawn there (`twin_suns` means no drawn sun). The other slots can still add to what you wrote",
      "Same note + same `seed:` → same world; renaming the note changes its world",
      "Ordinary values come up more often; what would clash or react violently is less likely, never impossible (engine setting “How much a clash steers the draw”)",
      "Drawn pages are marked in the book; ✓ keeps one as written, × removes it",
      "The “Solitude” setting weights the draw toward deserted worlds: more ruins and wild nature, fewer hunters",
      "Orbit, sun colours, world types, terrain, riches, scars and all the other blocks marked “never drawn” only exist if you write them"] },
    { h: "Home" },
    { p: "No return book **and** no fissure: the Age is a trap. With water, a drawn fissure lies underwater." },
  ] },
  { id: "react", part: "gen", icon: "flask-conical", title: "Reactions (never written)", check: "products", body: [
    { p: "When two blocks of the Age meet, they can react and add a product to the world. Products appear by themselves in the description and in the book, and can react in turn." },
    { note: "Never write a product: it is not a block, and alone on its line it is an ink blot. Write its ingredients instead (`water` and `lava` give `obsidian`)." },
    { h: "Geology" },
    { ul: ["`obsidian` ← `water` + `lava`", "`ice` ← `water` + `deep_cold`", "`glass` ← `sand` + `lava`", "`rust` ← `water` + `iron`, or `acid` + `iron`", "`brine` ← `water` + `salt`", "`silt` ← `water` + `ash`", "`diamond` ← `ash` + `pressure`", "`humming_shard` ← `crystal` + `strange_stone`", "`crying_obsidian` ← `salt` + `obsidian`", "`fulgurite` ← `lightning` + `sand`"] },
    { h: "Weather" },
    { ul: ["`storm` ← `rain` + `wind`", "`thunderstorm` ← `storm` + `lightning`", "`marsh_mist` ← `fog` + `water`", "`dust_storm` ← `wind` + `sand`", "`ash_cloud` ← `wind` + `ash`", "`hail` ← `rain` + `deep_cold`", "`steam` ← `rain` + `lava`, or `heat` + `water`", "`rime` ← `fog` + `deep_cold`", "`meltwater` ← `heat` + `ice`", "`spore_cloud` ← `wind` + `spore`", "`charged_crystal` ← `lightning` + `crystal`", "`scented_mist` ← `fog` + `flowers`", "`petal_rain` ← `wind` + `flowers`", "`glaze` ← `drizzle` + `deep_cold`", "`crystal_rain` ← `drizzle` + `crystal`", "`ash_rain` ← `drizzle` + `ash`", "`acid_rain` ← `drizzle` + `acid`", "`meltwater` and `steam` also come from `snow` + `heat` and `snow` + `lava`"] },
    { h: "Life" },
    { ul: ["`moss` ← `spore` + `water`", "`lichen` ← `moss` + `deep_cold`", "`pale_fungus` ← `spore` + `ash`", "`sapling` ← `seed` + `water`", "`ironwood` ← `sapling` + `pressure`", "`cinderbloom` ← `seed` + `lava`", "`glowvine` ← `vine` + `crystal`", "`withered_fern` ← `fern` + `salt`, or `heat` + `fern`", "`charred_grove` ← `great_tree` + `lava`", "`grove` ← `great_tree` + `water`", "`wildfire` ← `lightning` + `great_tree`", "`lantern_moths` ← `moth` + `glowvine`", "`herd` ← `grazer` + `moss`", "`stalking_pack` ← `hunter` + `herd`", "`warren` ← `burrower` + `silt`", "`still_drifter` ← `drifter` + `deep_cold`"] },
    { h: "Ruins" },
    { ul: ["`worn_tablet` ← `tablet` + `water`", "`lit_lamp` ← `lamp` + `crystal`", "`sealed_door` ← `door` + `pressure`", "`blurred_book` ← `book` + `water`", "`fallen_bridge` ← `bridge` + `rust`", "`speaking_tablet` ← `tablet` + `strange_stone`"] },
    { p: "Violent reactions cost the most (up to 25 points); soothing, growing and crystallizing ones give a few points back. `acid` also turns `coral` into `salt`, `stone` into `hollowed_ground` and `water` into `bitter_water` (blocks that can also be written)." },
    { h: "Rare variants (with strange_stone)" },
    { p: "When `strange_stone` is in the Age, these products show as their rare variant:" },
    { ul: ["`whispering_obsidian`, `black_ice`, `singing_glass`, `living_rust`, `clouded_diamond`", "`whispering_storm`, `waiting_thunder`, `watching_mist`, `black_hail`", "`singing_lichen`, `wrong_glowvine`, `whispering_moths`, `watching_herd`, `humming_warren`"] },
  ] },
  { id: "physgen", part: "gen", icon: "orbit", title: "Physics of the world", body: [
    { p: "Beneath the blocks lies a small physical world: star, orbit, planet, inner heat, core, magnetic field, air, temperature, water, light. It is not a simulation: simplified laws, tuned so that Earth, Mars, Venus and the Moon come out roughly right. What the book leaves open is drawn from the seed, under constraints: the world looks for a physics that holds what you wrote (48 attempts, always the same for the same seed)." },
    { p: "The Details tab shows the result as a sheet. When something does not hold, it says why and proposes a line to write (`age: 3.5`); one click writes it into the block." },
    { h: "Modes (Settings › Ages & mechanics)" },
    { ul: ["**Easy** (default): the sheet explains, stability never changes. World types (`frozen_world`…) steer the draw", "**Strict**: each tension costs on its axis (light 10, medium 20, heavy 35 points, at most 45 per axis), multiplied by the “Physics severity” slider (0.5 to 2). World types no longer steer the draw: they are only checked", "**Off**: nothing"] },
    { h: "Builders" },
    { p: "Ruins (`tablet`, `door`, `bridge`, `lamp`, `book`, `library`, `garden`…) say that someone passed through: they may have brought what nature could not have made in time. They do not excuse impossible life. The Relto is outside physics: it is the safe zone." },
  ] },
  { id: "window", part: "gen", icon: "image", title: "What the window shows", body: [
    { p: "**Rendering**: `classic` (the engine's painted window) or `generative` (a landscape drawn from the seed: tinted sky, relief, vegetation, weather, reflections, foreground, one inhabited detail per Age). Unknown blocks are painted from their axis and adjectives." },
    { p: "In the generative window nothing is decorative: everything comes from the book and its physics." },
    { ul: ["**Shores**: water and land in the same Age share the bottom of the image; the shore follows what is written: lava (a black, smoking coast), sand (beach and dunes), ice (pack ice), stone or ruins (rocks), plants (a grassy bank). World types impose their own scenery and have no shore", "**Foreground**: rocks, branch, arch, vines, reeds, leaves, pillar, ice stalactites, or nothing; drawn according to the Age (reeds only near water, ice only if it freezes). Branches grow differently each time (burnt, snowy, mossy, flowering, needles…)", "**Visible physics**: the colour and size of the sun come from the star and the distance; thin air darkens the sky (stars in daylight, few clouds), thick air makes it milky; strong gravity flattens the relief, weak gravity raises it; a frozen face keeps the sun still; a cold or burning world shows", "**Nights**: each Age has its own sky: two to four constellations, sometimes a nebula or a band of stars, its moons (`moons:`); `few: stars` is respected", "**Below the surface**: `kelp`, `coral` and `acid` show in the water, in their place"] },
    { p: "**Effects** (`fx:` or setting): `classic` (tremors, shifting sky, fractures according to instability), `static` (snow), `ripple`, `sweep`, `tv` (old television), `random` (one effect per Age name), `off`. Intensity from 0.2 to 2; `prefers-reduced-motion` is respected." },
    { p: "**Damage** (drawn from the book's seed): `damaged_pages` = shifted zones, red/cyan split, frozen zones or ink blots; `removed_pages` = burnt holes with snow; strong instability = branching fractures. Up to 12 zones and 6 holes; `fx: off` removes them." },
  ] },
  { id: "trap", part: "gen", icon: "triangle-alert", title: "Traps, damaged books, links", body: [
    { ul: ["**Trap book** (`trap book`): no return (a `return:` line is ignored) and no fissure; it looks perfectly normal", "**Damaged book**: each `damaged_pages` adds 0.08 of linking instability, each `removed_pages` 0.15 (at most 0.9). It affects only the link, not the Age's stability. From 0.3, “Listen to the static” appears", "**Unreliable links** (setting): beyond 30% linking instability, “open ↗” or a click on the window may waver (it fails, try again) or slip (you land in another book of the same Age). At 85%: 35% waver and 24% stray"] },
  ] },
  { id: "mech", part: "gen", icon: "puzzle", title: "Mechanisms and solitude", body: [
    { p: "Each mechanism has a state (dormant, rusted, overgrown, sealed, cracked) and a puzzle (pressure mark, order, angles or tones), whose values are given in D'ni numerals. With the setting “Mechanisms: draw”, the Age invents up to two, chosen by what it holds (water calls for valves, crystal for sound locks…)." },
    { p: "Solitude: off (the original draw), balanced (ruins ×2.2, flora ×1.3, hunters ×0.5), strong (ruins ×3.5, hunters ×0.25). Changing this setting changes the worlds drawn for open slots." },
  ] },
  { id: "journal", part: "gen", icon: "notebook-pen", title: "Journal, cover, properties", body: [
    { ul: ["**Journal**: the command “Create the exploration journal for this Age” creates a note with an `age-journal` block, written from the notes that point back to the Age. Voices inspired by characters from the games (English or French)", "**Cover**: a tab of the book, procedural (marble, leather, brass, glyphs, medallion), from the most ornate to the barest; SVG export", "**Map**: the command “Generate the Age map (canvas)” draws the linked Ages (blue = round trip, orange = one way)"] },
    { p: "Properties written into the note (commands “Update Age data…” or the automatic setting): `age_verdict`, `age_stability`, `age_axes`, `age_return`, `age_links`, `age_discovered`, `age_drawn`, `age_home`, usable with Dataview or Bases." },
  ] },
  { id: "snd2", part: "gen", icon: "volume-2", title: "Sounds", body: [
    { ul: ["**Book**: a dull thud, leather, pages (“Book sound”), then 2 to 5 clasp clicks (“Clasp clicks”)", "**Linking**: eleven variants (A to K) drawn at random, never the same twice in a row, with random pitch, glissando, tremolo, echo, chord", "**Page turn**: a synthesised paper rustle", "**Static**: breath with dropouts and a 50 Hz hum", "**Ambiences**: wind, pines, water, waterfall, rain, drone, metallic resonance, fire, crickets, thunder, pad, chime; minimal / zen / full levels", "**Safeguard**: the ambience stops if the note changes, if the tab closes or goes to the background; it keeps going when you switch tabs inside the Relto"] },
  ] },

  // ---- Relto ------------------------------------------------------------------------------------------------------
  { id: "relto2", part: "relto", icon: "mountain", title: "The refuge: note and block", body: [
    { p: "The command “Open the Relto” creates the refuge note (in the refuge folder) if needed. A `relto` code block shows the island in any note:" },
    { code: "```relto\ninscription: Shorah\ntime: 21.5\n```" },
    { h: "Options of the relto block (one per line, all optional)" },
    { ul: ["`source: [[Relto]]`: the refuge note (otherwise the first note with `age_type: personal_hub`)", "`time: 21.5`: a fixed hour (otherwise the computer's clock)", "`inscription: Shorah`: a motto under the image", "`dni_time: off`: hides the D'ni time", "`pages: hide`: collapses the page list (tabless mode)", "`folders: Ages`, `exclude: Drafts`, `books: Sunder Reach, Glass Marsh`: which books stand on the shelf (comma-separated lists); otherwise the checkboxes of the Pages tab, saved as `relto_books` in the note (`[]` = no books)"] },
    { h: "The refuge note (properties)" },
    { code: "---\nage_type: personal_hub\nage_name: Relto\nseed: 19991118\nenvironment:\n  base_terrain: volcanic_plateau\n  surrounding: cloud_sea\n  sky_cycle: system_time\nstructures: [hut, bookshelves, linking_pillars]\nrelto_pages_active: [page_pine_trees, page_waterfall]\n---" },
    { ul: ["`base_terrain`: volcanic_plateau, mossy_plateau, sand_island, glacier, obsidian_plateau", "`surrounding`: cloud_sea, fog_sea, ocean, void, lava_sea", "`sky_cycle`: system_time, frozen_dawn, frozen_day, frozen_dusk, frozen_night"] },
    { h: "D'ni time" },
    { p: "Computed from the computer's clock: year (hahr), month (vailee), day (yahr), then gahrtahvo : tahvo : gorahn : prorahn, in D'ni numerals. A prorahn lasts about 1.39 s." },
  ] },
  { id: "reltopages", part: "relto", icon: "file-plus", title: "Relto pages", body: [
    { p: "Each page adds an element and an ambience to the island. Command “Create a Relto page” (or “New page” in the Pages tab) writes it as a note; attach it from the Pages tab." },
    { h: "Built-in pages" },
    { p: "`page_pine_trees`, `page_birches`, `page_palms`, `page_ferns`, `page_waterfall`, `page_fireflies`, `page_lanterns`, `page_snow`, `page_aurora`, `page_fireworks`, `page_mountain`, `page_pillars`, `page_chimney`, `page_mist`, and under the island: `page_gems`, `page_gold`, `page_silver`; then `page_rain`, `page_storm`, `page_birds`, `page_butterflies`, `page_moons`, `page_comets`, `page_dock`, `page_bench`, `page_islets`, `page_calendar`, `page_dni_clock`, `page_flowers`, `page_grass`, `page_ponderosa`, `page_maples`, `page_crystal_tree`, `page_stalk_tree`, `page_koi`, `page_pond_decor`, `page_cat`, `page_cat_toys` and `page_imager`." },
    { h: "A page = a note" },
    { code: "---\nrelto_page_id: page_pine_trees\ntarget_age: Relto\nenabled: true\neffects:\n  canvas_additions:\n    - { type: vegetation, density: 0.7, asset: conifer }\n  ambiance_audio: wind_in_pines\nunlock:\n  age: \"[[Marais de verre]]\"\n  min_stability: 60\n  ages_count: 3\n---" },
    { p: "Effect types: vegetation, waterfall, fireflies, lanterns, snow, aurora, mist, fireworks, mountain, pillars, chimney, gems, gold, silver, koi, cat, rain, storm, birds, butterflies, moons, dock, bench, stalktree, cattoys, ponddecor, islets, calendar, flowers, grass, imager, telescope, dniclock, comet. Ambiences: wind, wind_in_pines, waterfall, river, soft_rain, night_crickets, deep_hum, fire_crackle, hearth, stone_choir, mountain_air, fireworks, metal_chimes, thunder." },
    { p: "`comet` (page `page_comets`): now and then a comet slowly crosses the sky, mostly at night; its density is how often it comes (about every 8 minutes at 0, about every minute at 1). Each pass lasts 40 to 60 seconds and depends only on the Relto seed and the time." },
    { p: "States: *active*, *available* (Attach button), *locked* (reason shown), *disabled*, *missing*." },
    { h: "Pages in a relto-library block" },
    { p: "One page per line: `page id: Label | effects | audio=… | unlock=[[Age]]:60`." },
    { code: "```relto-library\npage lagoon: Lagoon | vegetation 0.5 palm, gold 0.6 | audio=river | unlock=[[Marais de verre]]:60\n```" },
  ] },
  { id: "reltocat", part: "relto", icon: "cat", title: "The cat, the Imager and the telescope", body: [
    { h: "The cat" },
    { p: "Page `page_cat`: `cat_name`, `cat_color` (black, white, orange, grey, cream, tabby, calico, tuxedo, siamese or #rrggbb), `cat_sleep` (auto, always, never). In auto, it sleeps on the cabin rug mostly at night (even more with the Chimney page) and in rain, storm or snow; the draw changes every half hour. Click it and it purrs. The koi pond (`page_koi`) has `koi_rare` (ogon, platinum, ghost) and `koi_name`." },
    { h: "The Imager" },
    { p: "Page `page_imager`: a machine on the cabin table, then its room. You set an Age's book on the lectern (‹ › to change book) and tune the machine until you see the Age on the brass screen. No tabs: a workbench and three stations, each with its lamp; click to move closer, the down arrow to step back." },
    { ul: ["**I · Crystal rack**: eight engraved crystals, four slots; you pick up a crystal and place it (the one that was there returns to the rack). The right answer: the book's written pages, in block order (the first four). Wrong: the image doubles; a right page in the wrong place glows amber and counts a little", "**II · Optical bench**: three glasses (red, green, blue) that slide on their rails = the light of its star (sun colour, black sun, or no star); the slatted iris = the light received; the comparator shows the star on the left, your beam on the right. Wrong: the image is tinted or darkened", "**III · Regulator**: polarity inverter, frequency, amplitude, harmonics, phase; cathode-ray tube and voltmeter. Frequency comes from the length of the day, amplitude from the air pressure, harmonics from auroras and the magnetic field; the phase drifts with the hour (barely at all if the cycle is frozen; an erratic cycle jumps every two hours)"] },
    { p: "Sharpness is the product of the three: everything must be tuned; the gauge gives the overall figure. **Lock**: on a sharp image (amber lamp), pull the lever: the machine follows the Age on its own, the controls are held, and the book carries a brass tag on the shelf. **Periscope** (locked): the crank turns the view (four directions, same sky, different scenery), the lever tilts it (zenith, horizon, underwater if there is water). Clues: the surveyor's notebook on the cabin table, and the Age's Details tab (a surveyor's note, more or less precise depending on the “Surveyor's notes” setting). Tuning, lock and periscope are kept per book." },
    { p: "**The Art of the Guild** (the demanding way to play the instruments, setting `instrumentsMode: guild`; the default, easy mode is the Imager above). The machine holds a single **blank book**, fixed in place (no ‹ ›), its window black: you do not choose the Age, you find it. The **telescope** gives the target: an Age's book on the observatory's lectern, its star already charted and the three wheels on its clues, the instrument holds that star and sends its light down; the station II comparator shows it on the left. Without it, the left half stays dark (you can still tune blind, from the surveyor's words). **Station I** offers crystals for the known glyphs (those written in the shelf's Ages, as in the book of glyphs; rows of eight, ‹ ›), four sockets: four crystals in order are the first pages of a world. When they match an Age (among those of the held star, otherwise among all), they **lock a planet** and wake **station III**: only then does the sky's trace appear on the cathode tube. Several Ages around one star (`system:`) share its light: crystals and atmosphere tell them apart. Fully tuned, the image forms and the book **remembers**: the Age's name is inscribed on its page. The sync micrometer (step 2), the lock and the periscope work as before. Wrong crystals double the image, wrong glass tints it, a wrong atmosphere snows, without naming the world; settings that match no written Age usually leave the window black." },
    { p: "**Worlds no one has written** (the Art of the Guild). The Art links to worlds that already exist, so tuning blind (the telescope holds no star) with four crystals that match no written Age can still fall on one. Station III then searches instead of sleeping. If the lenses name a plausible star, the day and the air are plausible, and the book judges a world with these four first pages, in this order, alive, then about one time in three the window forms a world no one has written; the same crystals, star light and notch ranges of iris, frequency and amplitude always show the same world, or nothing. Brought into focus, it has no name in the book (“a world no one has written”, a few words of its description), a strange tone sounds and a line says so. **Transcribe this world** writes a new note, never overwriting, with exactly its four pages, its star and sky as value lines (`star_mass:`, `insolation:`, `rotation:`, `atmosphere:`) and its `seed:`, under a generated name; opened, it is the same world, and a written Age from then on. A written Age whose pages match always wins." },
    { h: "The telescope" },
    { p: "Page `page_telescope`: always in the book of pages, locked until you have written a first Age and attached the Mountains page. A small observatory on the summit (stone drum, verdigris dome, open slit); click it to look through. Every Relto hides its own **Great Zero**, drawn from its name and seed. Two wheels: **Torahn** (the angle, clockwise from the Great Zero line, in torantee: a full turn is 62,500) and **Elevation** (height from the Great Zero plane, in shahfeetee; as on the KI, above the plane reads negative); the rim moves 25 notches, the hub one notch (100 torantee or 1 shahfee). These are the D'ni Great Zero Coordinate System (GZCS) units; the third coordinate, the distance from the Zero (in shahfeetee), is measured when an Age's star is charted (below). No distance is ever shown: a pulse in the glass, beating with the D'ni prorahn, brightens and steadies as you come closer, a line of words says what you see, and a soft tone follows each turn; in the easy way (default) the words add “It brightens.” or “It fades.” after each turn and the signal barely shimmers; in the Art of the Guild (setting “Way of the instruments”) nothing says whether you are getting closer, and the signal shimmers from beat to beat, so watch a few beats and compare. On the left wall a brass **metronome**, set by hand, beats the prorahn: it counts, it does not know the hour. The true Zero's pulse peaks each time the pendulum reaches the end of its swing (the stop it touches glows; with the close-up room sounds, a dry tick distinct from the pulse's note); anything else slides against it. With reduced motion it stays at rest and a small lamp marks the beat. Bring the point into the small ring: the Zero is found, engraved on the plate in D'ni numerals, and stays found (click the plate to set the wheels back on it). Finding the Zero unlocks the **D'ni clock** page (`page_dni_clock`): a brass armillary sphere on its own pillar in the mist, its hour ring turning with the D'ni day. Once it is attached, the observatory spreads the Zero's beam through the whole Relto: the D'ni hour appears and the calendar sets itself right. Click the sphere to see it up close (the clock button in the navigation too): four brass rings carry the D'ni units, from the outside in the vailee (one turn per hahr), the yahr (one per vailee), the gahrtahvo (one per yahr) and the tahvo (one per gahrtahvo), each engraved with its D'ni numerals and read under the fixed index at the top; when a unit changes, its digit glows for a moment, then fades. The plinth bears the date and hour in D'ni numerals and the vailee's name. Until then the Relto only knows the date by its calendar pinnacle, which drifts by a few yahr, and the hour is silent. (That the beam carries D'ni time is this plugin's own extension of the lore.) Step 2: once the Zero is found, lay an Age's book on the observatory's **lectern** (‹ ›). The wheels then aim where the Zero appears seen from that Age, and a third wheel sets the pulse's **Delay** (notches of 25 shahfeetee); an amber echo beats before or after the pulse until the delay is right. The clues are in the Age's Details tab (direction, height, delay, faintness; values in D'ni numerals when the notes are full). Within 200 torantee, 2 shahfeetee and one notch of delay, the Age's **star is charted** (the instrument computes its GZCS position itself). Ages with the same star blocks and the same `system: name` line share one star. With the star charted, the Imager gains a **sync micrometer**: in sync, a sharper image, the hour over there (also in the Details tab) and the KIPS coordinates; it drifts after a real week (worn off after two), sync again. Without calibration the Imager is unchanged." },
    { p: "Step 3, traps and difficulties (the Art of the Guild; in the easy way the old line never appears and dead stars only blur the image a little, the surveyor's notes telling the truth). **Dead stars**: some regions of space hold a pulsar, a neutron star or a black hole (`pulsar`, `neutron_star`, `black_hole`), written or not; nearby stars share them. A pulsar or neutron star adds a **false beat** at its own period (the surveyor's delay is wrong, and the amber echo can lock onto the false beat: nothing holds); a black hole **bends** the Zero's light (the surveyor's direction is wrong; in the eyepiece a bright image will not hold, the true point is the pale end of the arc). Such a star can still be charted by looking past the lure, or by **triangulation**: with two charted stars nearby, pull the **Beacons** lever and the bent light and false beat fall away. **The old line**: before you find the Zero, a second, paler pulse may catch your eye, slipping against the D'ni clock and the metronome (about 1.06 prorahn): the line of King Me'erta, never decreed. Lock onto it and the instrument holds that line: every star charted afterwards is turned by the same angle (the plate looks right, but the Age's hour and KIPS are wrong). Signs: on the **star chart** the lead line from each star misses the Zero, two Ages of one `system:` disagree, the Details tab says the star was engraved on an old line. To fix it, aim the true Zero again (the instrument settles on it) and chart the stars again, or scratch one off (the small cross on its plate). **The star chart**: the parchment roll on the observatory wall opens a map of the Zero, your Relto and every charted star with its Ages (names on hover) and its dead stars; one well-charted Age anchors it. **Drift**: Ages without a magnetic field (dead core, or a world that does not spin) give rough bearings (four or eight compass words instead of sixteen) and their calibration wears twice as fast; a weak field, 1.4 times; near a dead star, faster still." },
  ] },
];

module.exports = { REF_EN };
